import { execFileSync } from 'node:child_process'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { signaturePaymentPdfPatch } from './build/signaturePaymentPdfPatch.js'
import { signaturePaymentPdfExactPreviewPatch } from './build/signaturePaymentPdfExactPreviewPatch.js'
import { signaturePaymentPdfLargeFontPatch } from './build/signaturePaymentPdfLargeFontPatch.js'
import { signatureDocumentRefMatchWebPatch } from './build/signatureDocumentRefMatchWebPatch.js'
import { sidebarGroupsDefaultOpenPatch } from './build/sidebarGroupsDefaultOpenPatch.js'
import { signaturePaymentTopicFinalOverridePatch } from './build/signaturePaymentTopicFinalOverridePatch.js'
import { appealReviewHtmlCleanupPatch } from './build/appealReviewHtmlCleanupPatch.js'
import { appealRequestsOriginalCommentCleanupPatch } from './build/appealRequestsOriginalCommentCleanupPatch.js'
import { evaluationAgentFocusPopupPatch } from './build/evaluationAgentFocusPopupPatch.js'
import { qaTypingChallengeFeaturePatch } from './build/qaTypingChallengeFeaturePatch.js'
import { qaAccessCheckOverviewPatch } from './build/qaAccessCheckOverviewPatch.js'
import { qaAccessCheckPermissionPatch } from './build/qaAccessCheckPermissionPatch.js'
import { qaAccessCaseLinkPatchV2 } from './build/qaAccessCaseLinkPatchV2.js'
import { qaAccessCheckWriteFixPatch } from './build/qaAccessCheckWriteFixPatch.js'
import { qaAccessCheckDirectWriteFixPatch } from './build/qaAccessCheckDirectWriteFixPatch.js'
import { qaAccessCheckQueueVisibilityFixPatch } from './build/qaAccessCheckQueueVisibilityFixPatch.js'
import { qaEvaluationProgressPatch } from './build/qaEvaluationProgressPatch.js'
import { caseDetailPdfThaiWrapPatch } from './build/caseDetailPdfThaiWrapPatch.js'
import { investigationFindingsPatch } from './build/investigationFindingsPatch.js'
import { usernameIdentityPolicyPatchV2 } from './build/usernameIdentityPolicyPatchV2.js'
import { usernameMigrationBootstrapBypassPatch } from './build/usernameMigrationBootstrapBypassPatch.js'
import { userDirectoryPdfUserColumnPatch } from './build/userDirectoryPdfUserColumnPatch.js'
import { profilePdfPreferredNameEnglishPatch } from './build/profilePdfPreferredNameEnglishPatch.js'
import { teamChatV2Patch } from './build/teamChatV2Patch.js'
import { chatSendOnlineUiPatch } from './build/chatSendOnlineUiPatch.js'
import { chatOnlineTooltipPhotoPatch } from './build/chatOnlineTooltipPhotoPatch.js'
import { chatRealtimeBackendPatch } from './build/chatRealtimeBackendPatch.js'
import { firestoreQuotaProtectionPatch } from './build/firestoreQuotaProtectionPatch.js'
import { teamChatRoomsObserverPatch } from './build/teamChatRoomsObserverPatch.js'
import { teamChatRoomsUiPatch } from './build/teamChatRoomsUiPatch.js'
import { teamChatObserverPresencePatch } from './build/teamChatObserverPresencePatch.js'
import { chatRemoveOnlineOfflineFooterPatch } from './build/chatRemoveOnlineOfflineFooterPatch.js'
import { chatRemoveOnlineNowBlockPatch } from './build/chatRemoveOnlineNowBlockPatch.js'
import { summaryTopicTargetColorPatch } from './build/summaryTopicTargetColorPatch.js'
import { analyticsCompareTopicReportPatch } from './build/analyticsCompareTopicReportPatch.js'
import { analyticsScoreDriversPatch } from './build/analyticsScoreDriversPatch.js'
import { analyticsScoreDriversSummaryPatch } from './build/analyticsScoreDriversSummaryPatch.js'
import { analyticsCompareDirectIssuePatch } from './build/analyticsCompareDirectIssuePatch.js'
import { analyticsIntentScoreDriverSummaryPatch } from './build/analyticsIntentScoreDriverSummaryPatch.js'
import { analyticsCompareUiRedesignPatch } from './build/analyticsCompareUiRedesignPatch.js'
import { analyticsCompareInlineDifferencesPatch } from './build/analyticsCompareInlineDifferencesPatch.js'
import { analyticsCompareSinglePeriodPdfParityPatch } from './build/analyticsCompareSinglePeriodPdfParityPatch.js'
import { analyticsComparePdfDataParityPatch } from './build/analyticsComparePdfDataParityPatch.js'
import { analyticsBilingualTopicPdfPatch } from './build/analyticsBilingualTopicPdfPatch.js'
import { dynamicRolesAdminWorkspacePatch } from './build/dynamicRolesAdminWorkspacePatch.js'
import { dashboardUnifiedButtonStylePatch } from './build/dashboardUnifiedButtonStylePatch.js'

// Guarantee the monthly Signature PDF renderer is patched even when Vercel runs
// `vite build` directly and skips npm lifecycle/prebuild scripts.
execFileSync(process.execPath, ['./scripts/patch-signature-four-column-landscape-v98.mjs'], {
  stdio: 'inherit',
})

export default defineConfig({
  plugins: [signaturePaymentPdfPatch(), signaturePaymentPdfExactPreviewPatch(), signaturePaymentPdfLargeFontPatch(), signatureDocumentRefMatchWebPatch(), sidebarGroupsDefaultOpenPatch(), signaturePaymentTopicFinalOverridePatch(), appealReviewHtmlCleanupPatch(), appealRequestsOriginalCommentCleanupPatch(), evaluationAgentFocusPopupPatch(), qaTypingChallengeFeaturePatch(), qaAccessCheckOverviewPatch(), qaAccessCheckPermissionPatch(), qaAccessCaseLinkPatchV2(), qaAccessCheckWriteFixPatch(), qaAccessCheckDirectWriteFixPatch(), qaAccessCheckQueueVisibilityFixPatch(), qaEvaluationProgressPatch(), caseDetailPdfThaiWrapPatch(), investigationFindingsPatch(), usernameIdentityPolicyPatchV2(), usernameMigrationBootstrapBypassPatch(), userDirectoryPdfUserColumnPatch(), profilePdfPreferredNameEnglishPatch(), teamChatV2Patch(), chatSendOnlineUiPatch(), chatOnlineTooltipPhotoPatch(), chatRealtimeBackendPatch(), firestoreQuotaProtectionPatch(), teamChatRoomsObserverPatch(), teamChatRoomsUiPatch(), teamChatObserverPresencePatch(), chatRemoveOnlineOfflineFooterPatch(), chatRemoveOnlineNowBlockPatch(), summaryTopicTargetColorPatch(), analyticsCompareTopicReportPatch(), analyticsScoreDriversPatch(), analyticsScoreDriversSummaryPatch(), analyticsCompareDirectIssuePatch(), analyticsIntentScoreDriverSummaryPatch(), analyticsCompareUiRedesignPatch(), analyticsCompareInlineDifferencesPatch(), analyticsCompareSinglePeriodPdfParityPatch(), analyticsComparePdfDataParityPatch(), analyticsBilingualTopicPdfPatch(), dynamicRolesAdminWorkspacePatch(), dashboardUnifiedButtonStylePatch(), react()],
})
