import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import { classifyDay, temperatureBand, sceneFor, normalizeForecast, WEATHER_STATES } from '../src/weather/model.mjs';
import locate from '../api/weather-location.js';
import forecast from '../api/weather.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sample={weather_code:0,temperature_2m:30,cloud_cover:10,precipitation:0,is_day:1,time:Date.now()/1000};
for (const [patch,expected] of [[{},'clear'],[{temperature_2m:36},'hot'],[{weather_code:2},'partly-cloudy'],[{cloud_cover:95},'cloudy'],[{weather_code:61,precipitation:.5,cloud_cover:90},'light-rain'],[{weather_code:65,precipitation:4,cloud_cover:90},'rain'],[{weather_code:95},'thunderstorm'],[{weather_code:45},'fog'],[{precipitation:.5,cloud_cover:25},'sunshower']]) assert.equal(classifyDay({...sample,...patch}),expected);
assert.deepEqual([35,34,25,24,15,14].map(temperatureBand),['hot','normal','normal','cool','cool','cold']);
assert.equal(sceneFor({temp:28,base:'cloudy',isDay:false}).scene,'night-cloudy');
assert.equal(sceneFor({temp:28,base:'rain',isDay:false}).scene,'night-rain');
assert.equal(sceneFor({temp:36,base:'hot',isDay:false}).scene,'night');
const rise=100000,set=140000;
assert.equal(sceneFor({temp:28,base:'cloudy',isDay:true,sun:[[rise,set]]},(set+1)*1000).scene,'night-cloudy');
assert.equal(sceneFor({temp:28,base:'cloudy',isDay:false,sun:[[rise,set]]},(rise+1)*1000).scene,'cloudy');
const city={label:'กรุงเทพมหานคร',latitude:13.75,longitude:100.5,source:'manual'};
const payload={current:sample,hourly:{time:[sample.time-3600,sample.time],precipitation_probability:[10,80]},daily:{sunrise:[],sunset:[]},timezone:'Asia/Bangkok'};
assert.equal(normalizeForecast(payload,city).rainChance,80);
assert.throws(()=>normalizeForecast({...payload,current:{...sample,temperature_2m:null}},city));
assert.throws(()=>normalizeForecast({...payload,current:{...sample,time:sample.time-8000}},city));
console.log('PASS: all weather classes, temperature bands, missing values and sunrise/sunset transitions');
function response(){return {headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(data){this.body=data;return this;}};}
let res=response();locate({method:'GET',headers:{}},res);assert.equal(res.body.source,'fallback');assert.equal(res.body.label,'กรุงเทพมหานคร');
res=response();locate({method:'GET',headers:{'x-vercel-ip-city':'Bangkok','x-vercel-ip-country-region':'Bangkok','x-vercel-ip-latitude':'13.754321','x-vercel-ip-longitude':'100.501234'}},res);assert.equal(res.body.label,'Bangkok');assert.equal(res.body.latitude,13.75);assert.equal(res.headers['Cache-Control'],'private, no-store');
res=response();await forecast({method:'GET',query:{lat:'bad',lon:'0'}},res);assert.equal(res.statusCode,400);
const originalFetch=globalThis.fetch;let upstream;
globalThis.fetch=async url=>{upstream=new URL(url);return {ok:true,json:async()=>payload};};
res=response();await forecast({method:'GET',query:{lat:'13.75678',lon:'100.56789'}},res);assert.equal(upstream.searchParams.get('latitude'),'13.76');assert.equal(upstream.searchParams.get('timeformat'),'unixtime');assert.equal(res.statusCode,200);
globalThis.fetch=async()=>{throw new Error('offline');};res=response();await forecast({method:'GET',query:{lat:'13.75',lon:'100.5'}},res);assert.equal(res.statusCode,503);
console.log('PASS: coarse IP location, Bangkok fallback, provider failures and no precise coordinate storage');
const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'https://weather.qa.test/',pretendToBeVisual:true});
for(const key of ['window','document','localStorage','CustomEvent','Event','HTMLElement','Node','HTMLInputElement'])globalThis[key]=dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let modalOpens=0;
dom.window.HTMLDialogElement.prototype.showModal=function(){modalOpens++;this.open=true;};
dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
let gps=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(ok,fail){gps++;fail({code:1});}}});
let interval;const originalInterval=globalThis.setInterval;globalThis.setInterval=(callback)=>{interval=callback;return 1;};
fs.mkdirSync(path.join(root,'node_modules/.cache'),{recursive:true});
const tmp=fs.mkdtempSync(path.join(root,'node_modules/.cache/weather-test-'));
let app;
try {
 await build({stdin:{contents:'export * from "./src/weather/location.ts";export * from "./src/weather/store.ts";export * from "./src/weather/Weather.tsx";',resolveDir:root,loader:'ts'},outfile:path.join(tmp,'bundle.cjs'),bundle:true,format:'cjs',platform:'node',packages:'external',loader:{'.css':'empty'},logLevel:'silent'});
 const require=createRequire(import.meta.url),k=require(path.join(tmp,'bundle.cjs')),React=require('react'),{createRoot}=require('react-dom/client'),act=React.act;
 const urls=[];let fail=false;
 globalThis.fetch=async(url)=>{urls.push(String(url)); if(fail)throw new Error('offline');return {ok:true,json:async()=>String(url).includes('weather-location')?{...city,source:'ip'}:{...payload,current:{...sample,time:Date.now()/1000}}};};
 app=createRoot(document.getElementById('root'));
 await act(async()=>app.render(React.createElement(React.Fragment,null,React.createElement(k.WeatherHero,{title:'QA Dashboard',eyebrow:'PERFORMANCE'}),React.createElement(k.WeatherCollection))));
 const settle=async predicate=>{for(let i=0;i<30&&!predicate();i++)await act(async()=>await new Promise(r=>setTimeout(r,5)));assert.ok(predicate());};
 await act(async()=>k.chooseWeather());await settle(()=>document.querySelector('.weather-current strong').textContent==='30°C');
 assert.equal(gps,1);assert.equal(document.querySelectorAll('.weather-info').length,1);assert.equal(document.querySelector('h1').textContent,'QA Dashboard');assert.ok(document.querySelector('.weather-metrics').textContent.includes('80%'));
 await act(async()=>document.querySelector('.weather-place button').click());assert.equal(modalOpens,1);assert.equal(document.querySelector('dialog').open,true);
 await act(async()=>document.querySelector('dialog').dispatchEvent(new Event('cancel',{cancelable:true})));assert.equal(document.querySelector('dialog'),null);
 const requests=urls.length;await act(async()=>window.dispatchEvent(new Event('focus')));await act(async()=>interval());assert.equal(urls.length,requests,'focus/minute ticks do not refetch before expiry');
 await act(async()=>[...document.querySelectorAll('button')].find(button=>button.textContent==='ดู Night + Rain').click());assert.equal(document.documentElement.dataset.qaWeatherState,'weather-clear','preview does not change live state');
 assert.equal(document.querySelectorAll('.weather-scene-grid button').length,10);
 fail=true;await act(async()=>k.refreshWeather(true));assert.ok(document.querySelector('.weather-status').textContent.includes('แสดงข้อมูลล่าสุดที่มี'));assert.equal(document.querySelector('.weather-current strong').textContent,'30°C');
 await act(async()=>window.dispatchEvent(new CustomEvent('qa-appearance-change',{detail:{preference:'weekday-auto'}})));assert.equal(document.documentElement.dataset.qaWeatherCollection,undefined);assert.equal(gps,1);
 const beforeGps=localStorage.getItem('qa-dashboard:weather-city-v1');
 navigator.geolocation.getCurrentPosition=(ok)=>ok({coords:{latitude:13.77889,longitude:100.51234}});
 globalThis.fetch=async url=>{assert.match(url,/reverse-geocode/);return {ok:true,json:async()=>({label:'เขตบางพลัด, กรุงเทพมหานคร'})};};
 const located=await k.deviceCity(new AbortController().signal,true);assert.equal(located.label,'เขตบางพลัด, กรุงเทพมหานคร');assert.equal(located.source,'gps');assert.equal(located.latitude,13.78);assert.equal(localStorage.getItem('qa-dashboard:weather-city-v1'),beforeGps);
 globalThis.fetch=async()=>{throw Error('offline');};const unnamed=await k.deviceCity(new AbortController().signal,true);assert.match(unnamed.label,/ยังระบุชื่อพื้นที่ไม่ได้/);assert.equal(unnamed.source,'gps');
 const canceled=new AbortController();canceled.abort();assert.equal(await k.deviceCity(canceled.signal),null);
 console.log('PASS: automatic permission fallback, device district lookup, naming failure, cancellation, no GPS persistence and modal dialog');
 console.log('PASS: real React hero/collection, temperature, rain chance, preview isolation, refresh deduplication, cached failure display and clean theme switching');
}finally{if(app){const require=createRequire(import.meta.url);await require('react').act(async()=>app.unmount());}globalThis.setInterval=originalInterval;globalThis.fetch=originalFetch;dom.window.close();fs.rmSync(tmp,{recursive:true,force:true});}
for (const [id] of WEATHER_STATES)assert.ok(fs.existsSync(path.join(root,'public/weather',id+'.webp')),id+' asset');
for (const id of ['night-cloudy','night-rain','night-thunderstorm','night-fog'])assert.ok(fs.existsSync(path.join(root,'public/weather',id+'.webp')),id+' asset');
assert.doesNotMatch(fs.readFileSync(path.join(root,'index.html'),'utf8'),/weatherCollection|preciseLocationBridge/);
console.log('PASS: 10 distinct local scenes plus night variants; obsolete script layers removed');
