const AGENTS = [
 "Anucha Makundin",
 "Arisa aiemrit",
 "Chatkonnaphat Bhusomya",
 "Jariyawadee Taboodda",
 "Jureeporn Piddum",
 "Krivut Vongkampan",
 "Natcha Chai-in",
 "Nattapol Suprom",
 "Sunijtra Siritan",
 "Suphitcha Keawliam",
 "Wassana Phothong",
].sort((a, b) => a.localeCompare(b));
const USER_ACCOUNTS: UserAccount[] = [
 {
   username: "qa",
   password: "qa1234",
   displayName: "QA Admin",
   role: "QA",
 },
 {
   username: "supervisor",
   password: "super1234",
   displayName: "Supervisor",
   role: "Supervisor",
 },
 {
   username: "senior",
   password: "senior1234",
   displayName: "Senior",
   role: "Senior",
 },
 {
   username: "admin",
   password: "admin1234",
   displayName: "Admin",
   role: "Admin",
 },
 {
   username: "anucha",
   password: "Mk!A7p9#L2",
   displayName: "Anucha Makundin",
   role: "CS Customer-NonVoice",
   agentName: "Anucha Makundin",
 },
 {
   username: "arisa",
   password: "Ri$4Kq2@Zm",
   displayName: "Arisa aiemrit",
   role: "CS Customer-NonVoice",
   agentName: "Arisa aiemrit",
 },
 {
   username: "chatkonnaphat",
   password: "Ct#8Lm3!Qa",
   displayName: "Chatkonnaphat Bhusomya",
   role: "CS Customer-NonVoice",
   agentName: "Chatkonnaphat Bhusomya",
 },
 {
   username: "jariyawadee",
   password: "Jy@5Nx9#Wp",
   displayName: "Jariyawadee Taboodda",
    role: "CS Customer-NonVoice",
   agentName: "Jariyawadee Taboodda",
 },
 {
   username: "jureeporn",
   password: "Jp!6Vr2@Kd",
   displayName: "Jureeporn Piddum",
    role: "CS Customer-NonVoice",
   agentName: "Jureeporn Piddum",
 },
 {
   username: "krivut",
   password: "Kv#9Ts4!Mb",
   displayName: "Krivut Vongkampan",
    role: "CS Customer-NonVoice",
   agentName: "Krivut Vongkampan",
 },
 {
   username: "natcha",
   password: "Nc@7Pw3#Lf",
   displayName: "Natcha Chai-in",
    role: "CS Customer-NonVoice",
   agentName: "Natcha Chai-in",
 },
 {
   username: "nattapol",
   password: "Np!4Xz8@Hr",
   displayName: "Nattapol Suprom",
    role: "CS Customer-NonVoice",
   agentName: "Nattapol Suprom",
 },
 {
   username: "sunijtra",
   password: "Sj#6Qm1!Ty",
   displayName: "Sunijtra Siritan",
    role: "CS Customer-NonVoice",
   agentName: "Sunijtra Siritan",
 },
 {
   username: "suphitcha",
   password: "Sp@8Ld2#Vk",
   displayName: "Suphitcha Keawliam",
    role: "CS Customer-NonVoice",
   agentName: "Suphitcha Keawliam",
 },
 {
   username: "wassana",
   password: "Ws!3Kr7@Pn",
   displayName: "Wassana Phothong",
    role: "CS Customer-NonVoice",
   agentName: "Wassana Phothong",
 },
];
