import React, { useEffect, useMemo, useState } from 'react';
import { fetchCanonicalCoachingEvaluations } from './coachingCanonicalStore';
import { getStoredEvaluationMonthKey, type StoredEvaluation } from './evaluationStore';
import { fetchStoredCoachingRecords, saveMonthlyCoachingRecord, type StoredCoachingRecord, type CoachingRecordStatus } from './coachingStore';
import './monthlyCoaching.css';
import { scoreToGrade } from './lib/scoreIncentivePolicy';
import { uploadCoachingAttachment } from './coachingAttachmentUpload';
import { coachingEvaluationScope, resolveCoachingMonth, manualCoachingSummary, coachingStatusLabel, COACHING_WORKFLOW_START, isHistoricalCoachingMonth, coachingDisplayStatus, coachingMonthLabel, initialCoachingMonth, allowedCoachingStatuses, belongsToAgent, COACHING_STATUSES, currentCoachingMonth, monthlyCoachingId, restoreCoachingForm, seniorFor, coachingEndTime, followUpLabel, type CoachingAccount, type CoachingForm, type CoachingAction } from './monthlyCoachingModel';

type Props = { currentUser?: CoachingAccount | null; accounts: CoachingAccount[]; onOpenCase?: (caseId: string, agentName: string) => void };
const input = 'mc-input';
const button = 'mc-button';
const primary = 'mc-button mc-primary';
const card = 'mc-card';
const chip = 'mc-chip';
const readSession = (key: string) => { try { return JSON.parse(sessionStorage.getItem(key) || 'null'); } catch { return null; } };
const scoreOf = (rows: StoredEvaluation[]) => rows.length ? rows.reduce((sum, row) => sum + Number(row.finalScore || 0), 0) / rows.length : null;
const dateLabel = (date?: string) => date ? date.slice(0, 10).split('-').reverse().join('/') : '—';
function Status({value}:{value?:string}) {const tone=['Coaching แล้ว','Closed','No Coaching Required','Follow-up Next Month'].includes(value||'')?'green':['Waiting Senior','Action Plan Submitted','Appointment Scheduled'].includes(value||'')?'blue':'amber';return <span className={`mc-badge ${tone}`}>{coachingStatusLabel(value)}</span>;}
function Field({title,children}:{title:string;children:React.ReactNode}) {return <label className="mc-field"><span>{title}</span>{children}</label>;}
function topicPerformance(rows: StoredEvaluation[]) {
  const topics = new Map<string, { key: string; label: string; score: number; max: number; count: number; deductedCases: number; caseIds: string[] }>();
  rows.forEach(row => row.topics?.forEach(topic => {
    const key = `${topic.code}:${topic.title}`;
    const item = topics.get(key) || { key, label: topic.title, score: 0, max: 0, count: 0, deductedCases: 0, caseIds: [] };
    item.score += Number(topic.score || 0); item.max += Number(topic.max || 0); item.count++;
    if (Number(topic.score) < Number(topic.max)) { item.deductedCases++; if (row.caseId && !item.caseIds.includes(row.caseId)) item.caseIds.push(row.caseId); }
    topics.set(key, item);
  }));
  return [...topics.values()].map(t => ({ ...t, percentage: t.max ? t.score / t.max * 100 : 0, averageScore: t.score / t.count, maxScore: t.max / t.count }));
}

export default function MonthlyCoachingWorkspace({currentUser,accounts,onOpenCase}:Props) {
  const qa=currentUser?.role==='Quality Assurance';
  const viewKey=`qa-dashboard:monthly-coaching:view:${currentUser?.username}`;
  const [initialView]=useState(()=>readSession(viewKey));
  const [requestedMonth,setMonth]=useState(()=>initialCoachingMonth(initialView));
  const [selected,setSelected]=useState(initialView?.selected||'');
  const [view,setView]=useState<'detail'|'history'|'scores'>(initialView?.view||'detail');
  const [listView,setListView]=useState('list');const [page,setPage]=useState(1);
  const [team,setTeam]=useState('all');const [lead,setLead]=useState('all');const [status,setStatus]=useState('all');const [search,setSearch]=useState('');
  const [evaluations,setEvaluations]=useState<StoredEvaluation[]>([]);const [records,setRecords]=useState<StoredCoachingRecord[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
  useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([fetchCanonicalCoachingEvaluations(),fetchStoredCoachingRecords({allowCache:false})]).then(([rows,saved])=>{if(active){setEvaluations(rows);setRecords(saved);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[currentUser?.username,reload]);
  const scope=useMemo(()=>coachingEvaluationScope(accounts,currentUser,evaluations),[accounts,currentUser,evaluations]);
  const month=resolveCoachingMonth(requestedMonth,scope.months);
  const agents=useMemo(()=>scope.agents.filter(a=>scope.rowsByAgent.get(a.username)?.some(e=>getStoredEvaluationMonthKey(e)===month)),[scope,month]);
  const monthlyRows=(a:CoachingAccount)=>(scope.rowsByAgent.get(a.username)||[]).filter(e=>getStoredEvaluationMonthKey(e)===month);
  const recordFor=(a:CoachingAccount)=>records.filter(r=>r.monthKey===month&&belongsToAgent(a,r.agentId,r.agent)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];
  const statusFor=(a:CoachingAccount)=>coachingDisplayStatus(month,recordFor(a)?.status);
  const teams=[...new Set(agents.map(a=>a.teamName).filter(Boolean))];const leads=[...new Set(agents.map(a=>a.teamLead).filter(Boolean))];
  const matched=agents.filter(a=>(team==='all'||a.teamName===team)&&(lead==='all'||a.teamLead===lead)&&`${a.displayName} ${a.agentName} ${a.username}`.toLowerCase().includes(search.toLowerCase()));
  const visible=matched.filter(a=>status==='all'||statusFor(a)===status);
  const account=visible.find(a=>a.username===selected)||visible[0];
  const agentRows=account?scope.rowsByAgent.get(account.username)||[]:[];
  const agentMonths=[...new Set(agentRows.map(getStoredEvaluationMonthKey))].sort();
  const rows=account?monthlyRows(account):[];const topics=topicPerformance(rows);
  const agentRecords=account?records.filter(r=>belongsToAgent(account,r.agentId,r.agent)&&agentMonths.includes(r.monthKey)).sort((a,b)=>b.monthKey.localeCompare(a.monthKey)||b.updatedAt.localeCompare(a.updatedAt)):[];
  const record=agentRecords.find(r=>r.monthKey===month);const prior=agentRecords.find(r=>r.monthKey<month);
  const summary=[['ทั้งหมด',matched.length],['รอนัดหมาย',matched.filter(a=>['Draft','Waiting Appointment'].includes(statusFor(a)||'Draft')).length],['รอผลจาก Senior',matched.filter(a=>['Waiting Senior','Coaching In Progress','QA Reviewed'].includes(statusFor(a)||'')).length],['ปิดเคสแล้ว',matched.filter(a=>['Coaching แล้ว','Closed','No Coaching Required','Follow-up Next Month'].includes(statusFor(a)||'')).length]];
  const pages=Math.max(1,Math.ceil(visible.length/10));const currentPage=Math.min(page,pages);
  const setPeriod=(value:string)=>{setMonth(value);setView('detail');setNotice('');setPage(1);};
  const choose=(id:string)=>{setSelected(id);setView('detail');setNotice('');};
  useEffect(()=>{setPage(1);},[team,lead,status,search,month]);
  useEffect(()=>{if(loading)return;try{sessionStorage.setItem(viewKey,JSON.stringify({periodVersion:2,month,selected:account?.username||'',view}));}catch{/* Form reports storage errors separately. */}},[viewKey,month,account?.username,view,loading]);
  if(!currentUser)return null;
  const profile=account&&<section className="mc-profile"><Avatar account={account}/><div className="mc-profile-name"><h2>{account.displayName||account.agentName} <small>#{account.username}</small></h2><p>{record?.team||account.teamName||'ยังไม่มีทีม'} | Senior: {record?.seniorName||record?.coachedBy||account.teamLead||'ยังไม่ระบุ'}</p></div><div className={`mc-score ${scoreOf(rows)!>=85?'good':'bad'}`}><strong>{scoreOf(rows)?.toFixed(1)}%</strong><span>{scoreOf(rows)!>=85?'Passed':'Not Passed'}</span></div><Status value={coachingDisplayStatus(month,record?.status)}/><nav className="mc-tabs">{([['detail','ข้อมูล Coaching'],['history','ประวัติ Coaching'],['scores','ประวัติคะแนน']] as const).map(([key,title])=><button key={key} className={view===key?'active':''} disabled={busy} onClick={()=>setView(key)}>{title}</button>)}</nav></section>;
  const evidence=<EvidencePanel topics={topics} rows={rows} openCase={id=>onOpenCase?.(id,account?.agentName||account?.displayName||'')} busy={busy}/>;
  return <div className="mc-workspace"><header className="mc-header"><div className="mc-title"><Icon kind="chat"/><div><h1>Coaching</h1><p>วางแผน • ติดตาม • พัฒนารายบุคคล</p></div></div><div className="mc-filters">
    <Field title="เดือน"><div className="mc-month"><select aria-label="เดือน Coaching" className={input} value={month} disabled={busy||loading} onChange={e=>setPeriod(e.target.value)}>{!scope.months.length&&<option value="">ยังไม่มีผลประเมิน</option>}{scope.months.map(m=><option key={m} value={m}>{coachingMonthLabel(m)}</option>)}</select><button aria-label="เดือนถัดไปที่มีผลประเมิน" className={button} disabled={busy||scope.months.indexOf(month)>=scope.months.length-1} onClick={()=>setPeriod(scope.months[scope.months.indexOf(month)+1])}>›</button></div></Field>
    <Field title="ทีม"><select className={input} value={team} disabled={!qa||busy} onChange={e=>setTeam(e.target.value)}><option value="all">{qa?'ทุกทีม':'ทีมที่ดูแล'}</option>{teams.map(t=><option key={t}>{t}</option>)}</select></Field><Field title="Senior"><select className={input} value={lead} disabled={!qa||busy} onChange={e=>setLead(e.target.value)}><option value="all">{qa?'ทุก Senior':currentUser.displayName}</option>{leads.map(t=><option key={t}>{t}</option>)}</select></Field><Field title="สถานะ"><select className={input} value={status} disabled={busy} onChange={e=>setStatus(e.target.value)}><option value="all">ทุกสถานะ</option>{['Coaching แล้ว',...COACHING_STATUSES].map(s=><option key={s} value={s}>{coachingStatusLabel(s)}</option>)}</select></Field><Field title="ค้นหา Admin"><input className={input} value={search} disabled={busy} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหา Admin..."/></Field>
  </div></header><div className="mc-period"><span>{isHistoricalCoachingMonth(month)?'มกราคม–สิงหาคม 2026: Coaching แล้ว • ประวัติอ่านอย่างเดียว':'เฉพาะผู้มีผลประเมินในเดือนที่เลือก • ระบบใหม่เริ่มกันยายน 2026'}</span><div><button disabled={busy} onClick={()=>{setPeriod(resolveCoachingMonth(currentCoachingMonth(),scope.months));setStatus('all');}}>เดือนปัจจุบัน</button><button disabled={busy||loading} onClick={()=>setReload(n=>n+1)}>โหลดข้อมูลล่าสุด</button></div></div>
  {error&&<p role="alert" className="mc-alert">โหลดข้อมูลไม่ครบ: {error} กรุณาโหลดข้อมูลล่าสุดก่อนบันทึก</p>}{notice&&<p role="status" className="mc-notice">{notice}</p>}
  {loading?<div className={card} role="status">กำลังโหลดข้อมูล Coaching...</div>:<div className="mc-layout"><aside className="mc-roster"><nav className="mc-tabs"><button className={listView==='list'?'active':''} onClick={()=>setListView('list')}>รายการ Coaching</button><button className={listView==='calendar'?'active':''} onClick={()=>setListView('calendar')}>ปฏิทินนัดหมาย</button></nav><div className="mc-counts">{summary.map(([title,value],i)=><div key={title} className={`mc-count tone-${i}`}><span>{title}</span><strong>{value}</strong></div>)}</div>
  {listView==='calendar'?<AppointmentCalendar key={month} month={month} agents={visible} records={records.filter(r=>r.monthKey===month)} choose={choose} busy={busy}/>:<><div className="mc-search"><Icon kind="search"/><input aria-label="ค้นหาในรายการ Coaching" value={search} disabled={busy} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหา Admin..."/></div><div className="mc-list-head"><span>Admin</span><span>คะแนน<br/>(เดือนนี้)</span><span>สถานะ</span></div><div className="mc-list">{visible.slice((currentPage-1)*10,currentPage*10).map(a=><button className={`mc-person ${a.username===account?.username?'selected':''}`} key={a.username} disabled={busy} onClick={()=>choose(a.username)}><span className="mc-person-name"><Avatar account={a}/><span>{a.displayName||a.agentName}</span></span><strong className={scoreOf(monthlyRows(a))!>=85?'mc-good':'mc-bad'}>{scoreOf(monthlyRows(a))?.toFixed(1)}%</strong><Status value={statusFor(a)}/></button>)}</div>{!visible.length&&<p className="mc-empty">ไม่พบผู้มีผลประเมินตามตัวกรองนี้</p>}<div className="mc-pagination"><button className={button} aria-label="หน้าก่อนหน้า" disabled={currentPage<=1||busy} onClick={()=>setPage(currentPage-1)}>‹</button><span>{currentPage} / {pages}</span><button className={button} aria-label="หน้าถัดไป" disabled={currentPage>=pages||busy} onClick={()=>setPage(currentPage+1)}>›</button><p>แสดง {visible.length?(currentPage-1)*10+1:0}–{Math.min(currentPage*10,visible.length)} จาก {visible.length} รายการ</p></div></>}
  </aside><div className="mc-workbench">{account?view==='detail'&&month>=COACHING_WORKFLOW_START?<CoachingDetail key={`${currentUser.username}:${account.username}:${month}:${record?.updatedAt||'new'}`} currentUser={currentUser} accounts={accounts} account={account} month={month} record={record} prior={prior} rows={rows} topics={topics} blocked={Boolean(error)} intro={profile} evidence={evidence} onOpenCase={()=>onOpenCase?.(rows[0]?.caseId,account.agentName)} onBusy={setBusy} onSaved={saved=>{setRecords(rs=>[saved,...rs.filter(r=>r.id!==saved.id)]);setNotice(`บันทึกแล้ว • ${coachingStatusLabel(saved.status)}`);}}/>:<div className="mc-detail-grid"><main className="mc-center">{profile}{view==='detail'?<ArchivedCoaching month={month} record={record}/>:view==='history'?<section className={card}><h3>ประวัติ Coaching</h3>{[...agentMonths].reverse().map(m=>{const r=agentRecords.find(row=>row.monthKey===m);return <button className="mc-history-row" key={m} disabled={busy} onClick={()=>setPeriod(m)}><strong>{coachingMonthLabel(m)}</strong><Status value={coachingDisplayStatus(m,r?.status)}/><p>{manualCoachingSummary(r)||'ยังไม่มีบันทึกจาก QA'}</p>{r?.actions?.map(a=><p key={a.id}>{a.topic}: {a.plan} • {dateLabel(a.dueDate)} • {a.status}</p>)}</button>;})}</section>:<section className={card}><h3>ประวัติคะแนน</h3>{agentMonths.map((m,i)=>{const cases=agentRows.filter(e=>getStoredEvaluationMonthKey(e)===m);const previous=topicPerformance(agentRows.filter(e=>getStoredEvaluationMonthKey(e)===agentMonths[i-1]));return <div className="mc-history-row" key={m}><strong>{coachingMonthLabel(m)} • {scoreOf(cases)?.toFixed(1)}% • {cases.length} เคส</strong><div className="mc-chips">{topicPerformance(cases).map(t=>{const old=previous.find(p=>p.key===t.key);const delta=old?t.percentage-old.percentage:null;return <span className={chip} key={t.key}>{t.label} {t.percentage.toFixed(1)}% {delta===null?'':delta>0.5?'↑ ดีขึ้น':delta<-.5?'↓ ลดลง':'= เท่าเดิม'}</span>;})}</div></div>;})}</section>}</main><aside className="mc-evidence">{evidence}</aside></div>:<div className="mc-empty">ยังไม่มีผลประเมินที่ตรงกับผู้ใช้และตัวกรองที่เลือก</div>}</div></div>}
  </div>;
}
function Avatar({account}:{account:CoachingAccount}) {return <span className="mc-avatar" aria-hidden="true">{(account.displayName||account.agentName||account.username).split(' ').filter(Boolean).map(s=>s[0]).slice(0,2).join('')}</span>;}
function Icon({kind}:{kind:'chat'|'search'|'upload'}) {return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{kind==='chat'?<><path d="M4 3h16v14H9l-5 4z"/><path d="M8 7h8M8 11h6"/></>:kind==='search'?<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>:<><path d="M12 17V3m-5 5 5-5 5 5M4 15v6h16v-6"/></>}</svg>;}
function SectionTitle({number,children}:{number:number;children:React.ReactNode}) {return <h3 className="mc-section-title"><span>{number}</span>{children}</h3>;}
function AppointmentCalendar({month,agents,records,choose,busy}:{month:string;agents:CoachingAccount[];records:StoredCoachingRecord[];choose:(id:string)=>void;busy:boolean}) {
  const [calendarMonth,setCalendarMonth]=useState(month||currentCoachingMonth());const [year,mon]=calendarMonth.split('-').map(Number);
  const offset=new Date(Date.UTC(year,mon-1,1)).getUTCDay();const days=new Date(Date.UTC(year,mon,0)).getUTCDate();
  const meetings=records.filter(r=>r.appointment?.date?.startsWith(calendarMonth)&&agents.some(a=>belongsToAgent(a,r.agentId,r.agent))).sort((a,b)=>(a.appointment!.date+a.appointment!.startTime).localeCompare(b.appointment!.date+b.appointment!.startTime));
  const move=(delta:number)=>setCalendarMonth(new Date(Date.UTC(year,mon-1+delta,1)).toISOString().slice(0,7));
  return <div className="mc-calendar"><div className="mc-calendar-title"><button className={button} aria-label="ปฏิทินเดือนก่อน" onClick={()=>move(-1)}>‹</button><strong>{coachingMonthLabel(calendarMonth)}</strong><button className={button} aria-label="ปฏิทินเดือนถัดไป" onClick={()=>move(1)}>›</button></div><div className="mc-days">{['อา','จ','อ','พ','พฤ','ศ','ส'].map(d=><b key={d}>{d}</b>)}{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${calendarMonth}-${String(i+1).padStart(2,'0')}`;return <span key={date} className={meetings.some(r=>r.appointment?.date===date)?'has-meeting':''}>{i+1}</span>;})}</div>{meetings.map(r=><button key={r.id} disabled={busy} className="mc-meeting" onClick={()=>choose(agents.find(a=>belongsToAgent(a,r.agentId,r.agent))!.username)}><strong>{r.agent}</strong><span>{dateLabel(r.appointment?.date)} • {r.appointment?.startTime} • {r.appointment?.method}</span><Status value={r.status}/></button>)}{!meetings.length&&<p className="mc-empty">ยังไม่มีนัดหมายที่บันทึกในเดือนนี้</p>}</div>;
}
// StoredEvaluation.auditDate is Case Date; auditTimestamp is the QA audit time.
function EvidencePanel({topics,rows,openCase,busy}:{topics:ReturnType<typeof topicPerformance>;rows:StoredEvaluation[];openCase:(id:string)=>void;busy:boolean}) {
  const [all,setAll]=useState(false);const issues=rows.filter(r=>r.criticalError||r.topics?.some(t=>t.score<t.max));
  return <><section className="mc-evidence-card"><h3>ผลคะแนนรายหัวข้อ (เดือนนี้)</h3><div className="mc-topic-bars">{topics.map(t=><div key={t.key}><span>{t.label}</span><div className="mc-bar"><i className={t.percentage>=85?'good':t.percentage>=75?'warn':'bad'} style={{width:`${Math.max(0,Math.min(100,t.percentage))}%`}}/></div><small>{t.averageScore.toFixed(1)}/{t.maxScore.toFixed(1)}</small></div>)}</div></section><section className="mc-critical"><h3>⚠ Critical Error</h3>{rows.some(r=>r.criticalError)?rows.filter(r=>r.criticalError).map(r=><button key={r.id} disabled={busy} onClick={()=>openCase(r.caseId)}>{r.caseId} • เปิดดูรายละเอียด</button>):<p>ไม่พบ Critical Error ในเดือนนี้</p>}</section><section className="mc-evidence-card"><div className="mc-row-title"><h3>เคสตัวอย่างที่พบปัญหา</h3>{issues.length>3&&<button onClick={()=>setAll(!all)}>{all?'ย่อรายการ':`ดูทั้งหมด (${issues.length})`}</button>}</div><div className="mc-table-wrap"><table><thead><tr><th>Case ID</th><th>วันที่เคส</th><th>หัวข้อที่ถูกหัก</th></tr></thead><tbody>{(all?issues:issues.slice(0,3)).map(r=><tr key={r.id}><td><button disabled={busy} onClick={()=>openCase(r.caseId)}>{r.caseId}</button></td><td>{dateLabel(r.auditDate||String(r.rawDataPreview?.['Case Date']||r.rawDataPreview?.case_date||''))}</td><td>{r.topics?.filter(t=>t.score<t.max).map(t=>t.title).join(', ')||'Critical Error'}</td></tr>)}</tbody></table></div>{!issues.length&&<p className="mc-empty">ไม่พบเคสที่ถูกหักคะแนน</p>}</section></>;
}
function ScoreOverview({rows,topics,openCase}:{rows:StoredEvaluation[];topics:ReturnType<typeof topicPerformance>;openCase:()=>void}) {
 const score=scoreOf(rows);return <section className={card}><div className="mc-row-title"><SectionTitle number={1}>ผลการประเมิน (เดือนที่เลือก)</SectionTitle><button disabled={!rows.length} onClick={openCase}>ดูรายละเอียดเคส ›</button></div><div className="mc-metrics"><div>คะแนนรวม<strong className={score!>=85?'mc-good':'mc-bad'}>{score?.toFixed(1)}%</strong></div><div>KPI Status<span className={`mc-badge ${score!>=85?'green':'red'}`}>{score!>=85?'Passed':'Not Passed'}</span></div><div>จำนวนเคส<strong>{rows.length}</strong></div><div>Critical Error<strong className="mc-bad">{rows.filter(r=>r.criticalError).length}</strong></div><div>หัวข้อที่ถูกหักหลัก<div className="mc-chips">{topics.filter(t=>t.deductedCases).map(t=><span className="mc-badge red" key={t.key}>{t.label}</span>)}{!topics.some(t=>t.deductedCases)&&<span>ไม่มี</span>}</div></div></div></section>;
}
function PreviousCoaching({prior,topics}:{prior?:StoredCoachingRecord;topics:ReturnType<typeof topicPerformance>}) {
 return <section className={card}><div className="mc-row-title"><SectionTitle number={2}>ประวัติการ Coaching ล่าสุด{prior?` (${coachingMonthLabel(prior.monthKey)})`:''}</SectionTitle>{prior&&<Status value={coachingDisplayStatus(prior.monthKey,prior.status)}/>}</div><p className="mc-manual-note">{manualCoachingSummary(prior)||'ยังไม่มีบันทึกจาก QA'}</p>{Boolean(prior?.actions?.length)&&<div className="mc-table-wrap"><table><thead><tr><th>หัวข้อที่คุย</th><th>Action Plan เดือนก่อน</th><th>ผลเดือนนี้</th></tr></thead><tbody>{prior!.actions!.map(a=>{const now=topics.find(t=>t.label===a.topic);const old=prior!.topicSnapshot?.find(t=>t.label===a.topic);const label=now?followUpLabel(now,old,true):'';return <tr key={a.id}><td>{a.topic}</td><td>{a.plan}</td><td><span className={`mc-badge ${label==='Improved'?'green':'red'}`}>{label==='Improved'?'ดีขึ้น':label==='Still Needs Improvement'?'ยังพบปัญหา':label==='No Change'?'คงเดิม':'ยังไม่มีข้อมูล'}</span></td></tr>;})}</tbody></table></div>}{prior?.actualCoaching?.finalNote&&<p className="mc-manual-note">Senior: {prior.actualCoaching.finalNote}</p>}</section>;
}

function ArchivedCoaching({month,record}: {month:string;record?:StoredCoachingRecord}) {
  return <section className={card}><h3 className="text-lg font-bold">{coachingMonthLabel(month)} · {isHistoricalCoachingMonth(month)?'Coaching แล้ว':'ประวัติ Coaching'}</h3><p className="mt-2 text-sm text-slate-600">ระบบใหม่เริ่มกันยายน 2026 ไม่ต้องกรอกนัดหมายหรือ Action Plan ย้อนหลัง</p>{record ? <div className="mt-4 space-y-3 whitespace-pre-wrap text-sm"><p>{manualCoachingSummary(record)||'ยังไม่มีบันทึกจาก QA'}</p><p>{record.actualCoaching?.finalNote||record.additionalNote}</p><p>{record.actionPlan||record.agreedActionPlan}</p>{record.actions?.map(a=><p key={a.id}>{a.topic}: {a.plan} · {dateLabel(a.dueDate)}</p>)}{record.attachments?.map(a=><a key={a.path} className="block text-violet-700 underline" href={/^https:\/\//i.test(a.url)?a.url:undefined} target="_blank" rel="noreferrer">{a.name}</a>)}</div> : <p className="mt-4 text-sm text-slate-500">ไม่มีรายละเอียดบันทึกย้อนหลังในระบบ</p>}</section>;
}

type DetailProps = { currentUser: CoachingAccount; accounts: CoachingAccount[]; account: CoachingAccount; month: string; record?: StoredCoachingRecord; prior?: StoredCoachingRecord; rows: StoredEvaluation[]; topics: ReturnType<typeof topicPerformance>; blocked: boolean; intro: React.ReactNode; evidence: React.ReactNode; onOpenCase: ()=>void; onBusy: (busy:boolean)=>void; onSaved: (record:StoredCoachingRecord)=>void };
function CoachingDetail({currentUser,accounts,account,month,record,prior,rows,topics,blocked,intro,evidence,onOpenCase,onBusy,onSaved}: DetailProps) {
  const defaultParticipants = [account.displayName||account.agentName,record?.seniorName||account.teamLead||''];
  const formKey = `qa-dashboard:monthly-coaching:editing:${currentUser.username}:${account.username}:${month}`;
  const [form,setForm]=useState<CoachingForm>(()=>restoreCoachingForm(record,readSession(formKey),currentUser.role));
  const [participantToAdd,setParticipantToAdd]=useState('');
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const allowed=allowedCoachingStatuses(currentUser.role,record); const qa=currentUser.role==='Quality Assurance';
  const qaEdit=qa&&allowed.includes('Draft')&&!busy&&!blocked; const seniorEdit=!qa&&allowed.includes('Coaching In Progress')&&!busy&&!blocked; const reviewEdit=qa&&allowed.includes('QA Reviewed')&&!busy&&!blocked;
  const availableTopics=[...new Set([...topics.map(t=>t.label),...form.topics])];
  const participantKey=(value:string)=>value.trim().toLocaleLowerCase('en-US');
  const defaultParticipantKeys=new Set(defaultParticipants.map(participantKey).filter(Boolean));
  const extraParticipants=[...new Set(form.appointment.participants.map(name=>name.trim()).filter(Boolean).filter(name=>!defaultParticipantKeys.has(participantKey(name))))];
  const selectedParticipantKeys=new Set([...defaultParticipants,...extraParticipants].map(participantKey).filter(Boolean));
  const participantOptions=[...new Set(accounts.filter(item=>item.status!=='Suspended').map(item=>(item.displayName||item.agentName||item.username).trim()).filter(Boolean).filter(name=>!selectedParticipantKeys.has(participantKey(name))))].sort((a,b)=>a.localeCompare(b));

  const followUp=topics.map(t=>({...t,result:followUpLabel(t,prior?.topicSnapshot?.find(p=>p.label===t.label),prior?.recommendedTopics?.includes(t.label)||prior?.actions?.some(a=>a.topic===t.label))}));
  const update=(patch:Partial<CoachingForm>)=>{const next={...form,...patch};setForm(next);try{sessionStorage.setItem(formKey,JSON.stringify(next));}catch{setMessage('เบราว์เซอร์เก็บข้อความชั่วคราวไม่สำเร็จ กรุณาบันทึกก่อนออกจากหน้า');}};
  const appointment=(patch:Partial<CoachingForm['appointment']>)=>update({appointment:{...form.appointment,...patch}});
  const addParticipant=()=>{
    const name=participantToAdd.trim();
    if(!qaEdit||!name)return;
    appointment({participants:[...extraParticipants,name]});
    setParticipantToAdd('');
  };
  const removeParticipant=(name:string)=>{
    if(!qaEdit)return;
    const key=participantKey(name);
    appointment({participants:extraParticipants.filter(item=>participantKey(item)!==key)});
  };
  const result=(patch:Partial<CoachingForm['result']>)=>update({result:{...form.result,...patch}});
  const pending=(value:boolean)=>{setBusy(value);onBusy(value);};
  const save=async(status:CoachingRecordStatus)=>{
    if(blocked||busy||!rows.length||!allowed.includes(status))return;
    pending(true);setMessage('');
    try{
      const now=new Date().toISOString();const average=scoreOf(rows);const owner=seniorFor(accounts,account);
      const candidate:StoredCoachingRecord={...record,id:record?.id||monthlyCoachingId(account.username,month),agentId:record?.agentId||account.username,agent:record?.agent||account.agentName||account.displayName,team:record?.team||account.teamName||'',teamId:record?.teamId||account.teamName||'',seniorId:record?.seniorId||owner?.username||'',seniorName:record?.seniorName||record?.coachedBy||account.teamLead||'',monthKey:month,monthLabel:month,coachingDate:form.result.date||record?.coachingDate||'',coachedBy:record?.coachedBy||account.teamLead||'',evaluatedCases:rows.length,averageScore:average??record?.averageScore??0,grade:average===null?record?.grade||'':scoreToGrade(average,month),criticalErrors:rows.filter(e=>e.criticalError).length,strengths:record?.strengths||'',mainIssues:record?.mainIssues||'',repeatedIssues:record?.repeatedIssues||'',coachingRecommendation:record?.coachingRecommendation||'',actionPlan:record?.actionPlan||'',followUpDate:record?.followUpDate||'',result:record?.result||'Pending Review',status,caseReferences:rows.map(e=>e.caseId).filter(Boolean),topicSnapshot:topics.map(t=>({key:t.key,label:t.label,averageScore:t.averageScore,maxScore:t.maxScore,percentage:t.percentage,deductedCases:t.deductedCases,caseIds:t.caseIds})),checklistItems:record?.checklistItems||[],generalFeedback:record?.generalFeedback||'',agentResponse:record?.agentResponse||'',agreedActionPlan:record?.agreedActionPlan||'',additionalNote:record?.additionalNote||'',qaSummary:form.summary,recommendedTopics:form.topics,appointment:{...form.appointment,participants:[...new Set([account.displayName||account.agentName,record?.seniorName||account.teamLead||'',...form.appointment.participants].map(s=>s.trim()).filter(Boolean))]},actualCoaching:form.result,actions:form.actions,qaReviewComment:form.review,attachments:form.attachments,createdAt:record?.createdAt||now,updatedAt:now};
      const saved=await saveMonthlyCoachingRecord(candidate,currentUser,accounts,record?.updatedAt??null);
      sessionStorage.removeItem(formKey);onSaved(saved);
    }catch(e){setMessage(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{pending(false);}
  };
  const upload=async(file?:File)=>{if(!file||(!qaEdit&&!seniorEdit))return;pending(true);try{const attachment=await uploadCoachingAttachment(file,record?.id||monthlyCoachingId(account.username,month),currentUser.displayName);update({attachments:[...form.attachments,attachment]});setMessage('ไฟล์อัปโหลดแล้ว กรุณากดบันทึกเพื่อเชื่อมกับ Coaching');}catch(e){setMessage(e instanceof Error?e.message:'อัปโหลดไม่สำเร็จ');}finally{pending(false);}};
  const actions:[string,CoachingRecordStatus][] = qa ? [['บันทึก Draft','Draft'],['รอนัดหมาย','Waiting Appointment'],['นัดหมาย','Appointment Scheduled'],['ส่งให้ Senior','Waiting Senior'],['รับแผน','Follow-up Next Month'],['ส่งคืน Senior','QA Reviewed'],['ไม่ต้อง Coaching','No Coaching Required'],['ปิดเคส','Closed']] : [['บันทึกผล','Coaching In Progress'],['ส่ง Action Plan ให้ QA','Action Plan Submitted']];
  return <div className="mc-detail-grid"><main className="mc-center">{intro}<ScoreOverview rows={rows} topics={topics} openCase={onOpenCase}/><PreviousCoaching prior={prior} topics={topics}/>
    <section className={card}><SectionTitle number={3}>QA สรุปและแนะนำหัวข้อการ Coaching (เดือนนี้)</SectionTitle><div className="mc-summary-grid"><Field title="สรุปภาพรวมสำหรับ Senior"><textarea aria-label="QA Summary" className={input} value={form.summary} readOnly={!qaEdit} onChange={e=>update({summary:e.target.value})} placeholder="พิมพ์สรุปผลและเรื่องที่ต้องการแจ้ง Senior..."/></Field><div className="mc-topic-select"><strong>หัวข้อที่แนะนำให้คุยในเดือนนี้</strong>{availableTopics.map(t=><label key={t}><input type="checkbox" checked={form.topics.includes(t)} disabled={!qaEdit} onChange={e=>update({topics:e.target.checked?[...form.topics,t]:form.topics.filter(x=>x!==t)})}/><span>{t}{topics.some(p=>p.label===t&&p.deductedCases)?<small className="mc-bad"> (พบปัญหา)</small>:null}</span></label>)}</div></div></section>
    <section className={card}><SectionTitle number={4}>นัดหมาย Coaching</SectionTitle><div className="mc-appointment-grid"><Field title="วันที่นัดหมาย"><input type="date" className={input} value={form.appointment.date} disabled={!qaEdit} onChange={e=>appointment({date:e.target.value})}/></Field><Field title="เวลาเริ่ม (24 ชั่วโมง)"><input type="time" className={input} value={form.appointment.startTime} disabled={!qaEdit} onChange={e=>appointment({startTime:e.target.value})}/></Field><Field title="ระยะเวลา (นาที)"><select className={input} value={form.appointment.duration} disabled={!qaEdit} onChange={e=>appointment({duration:Number(e.target.value)})}>{[...new Set([15,30,45,60,90,120,180,form.appointment.duration])].sort((a,b)=>a-b).map(n=><option key={n} value={n}>{n>=60?`${n/60} ชั่วโมง`:`${n} นาที`}</option>)}</select></Field><Field title="ช่องทาง"><select className={input} value={form.appointment.method} disabled={!qaEdit} onChange={e=>appointment({method:e.target.value})}><option>Face to Face</option><option>MS Teams</option><option>Other</option></select></Field></div><p className="mc-muted">เวลาสิ้นสุด {coachingEndTime(form.appointment.startTime,form.appointment.duration)||'—'}</p>
    {form.appointment.method==='MS Teams'&&<Field title="ลิงก์ประชุม (MS Teams)"><input aria-label="MS Teams URL" className={input} type="url" placeholder="https://teams.microsoft.com/..." value={form.appointment.url} disabled={!qaEdit} onChange={e=>appointment({url:e.target.value})}/></Field>}{form.appointment.method==='Other'&&<Field title="รายละเอียดช่องทาง"><input aria-label="รายละเอียดช่องทาง" className={input} value={form.appointment.other} disabled={!qaEdit} onChange={e=>appointment({other:e.target.value})}/></Field>}
    <div className="mc-agenda-grid"><div><h4>Agenda / แพลนที่จะคุย</h4>{form.appointment.agenda.map((text,i)=><div key={i} className="mc-agenda-row"><b>{i+1}</b><input aria-label={`Agenda ${i+1}`} className={input} value={text} disabled={!qaEdit} onChange={e=>appointment({agenda:form.appointment.agenda.map((x,j)=>i===j?e.target.value:x)})}/><button aria-label={`ลบ Agenda ${i+1}`} className="mc-remove" disabled={!qaEdit} onClick={()=>appointment({agenda:form.appointment.agenda.filter((_,j)=>i!==j)})}>×</button></div>)}<button className={button} disabled={!qaEdit} onClick={()=>appointment({agenda:[...form.appointment.agenda,'']})}>+ เพิ่ม Agenda</button></div><div><h4>ผู้เข้าร่วม</h4><div className="mc-chips"><span className={chip}>{account.displayName||account.agentName}</span><span className={chip}>{record?.seniorName||account.teamLead||'ยังไม่ระบุ Senior'} (Senior)</span>{extraParticipants.map(name=><span className={`${chip} gap-1`} key={name}>{name}{qaEdit?<button type="button" aria-label={`ลบผู้เข้าร่วม ${name}`} className="ml-1 text-slate-500 hover:text-rose-600" onClick={()=>removeParticipant(name)}>×</button>:null}</span>)}</div><Field title="เพิ่มผู้เข้าร่วม"><div className="flex gap-2"><select aria-label="เลือกผู้เข้าร่วมเพิ่มเติม" className={input} value={participantToAdd} disabled={!qaEdit||!participantOptions.length} onChange={e=>setParticipantToAdd(e.target.value)}><option value="">{participantOptions.length?'เลือกชื่อผู้เข้าร่วม':'ไม่มีรายชื่อเพิ่มเติม'}</option>{participantOptions.map(name=><option key={name} value={name}>{name}</option>)}</select><button type="button" className={button} disabled={!qaEdit||!participantToAdd} onClick={addParticipant}>+ เพิ่ม</button></div></Field></div><Field title="หมายเหตุ (ถ้ามี)"><textarea aria-label="หมายเหตุนัดหมาย" className={input} value={form.appointment.note} disabled={!qaEdit} onChange={e=>appointment({note:e.target.value})} placeholder="ระบุหมายเหตุเพิ่มเติม..."/></Field></div></section>
    <details className={card} open={!qa}><summary className="cursor-pointer font-bold">ผล Coaching และ Action Plan โดย Senior</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field title="วันที่ Coaching จริง"><input type="date" className={input} value={form.result.date} disabled={!seniorEdit} onChange={e=>result({date:e.target.value})}/></Field><Field title="เวลาเริ่มจริง"><input type="time" className={input} value={form.result.startTime} disabled={!seniorEdit} onChange={e=>result({startTime:e.target.value})}/></Field><Field title="เวลาสิ้นสุดจริง"><input type="time" className={input} value={form.result.endTime} disabled={!seniorEdit} onChange={e=>result({endTime:e.target.value})}/></Field></div><h4 className="mt-3 text-sm font-semibold">หัวข้อที่คุยจริง</h4><div className="mt-2 flex flex-wrap gap-2">{form.topics.map(t=><label key={t} className={`${chip} gap-2`}><input type="checkbox" checked={form.result.topics.includes(t)} disabled={!seniorEdit} onChange={e=>result({topics:e.target.checked?[...form.result.topics,t]:form.result.topics.filter(x=>x!==t)})}/>{t}</label>)}</div><textarea aria-label="Senior Coaching Note" className={`${input} mt-3`} value={form.result.note} disabled={!seniorEdit} onChange={e=>result({note:e.target.value})} placeholder="Senior Coaching Note"/><textarea aria-label="Senior Final Note" className={`${input} mt-3`} value={form.result.finalNote} disabled={!seniorEdit} onChange={e=>result({finalNote:e.target.value})} placeholder="Senior Final Note"/>
      <h4 className="mt-3 font-semibold">Action Plan รายหัวข้อ</h4>{form.actions.map((action,i)=><div key={action.id} className="mt-3 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 sm:grid-cols-2">{(['topic','issue','plan','owner','dueDate','expectedResult','followUpNote'] as const).map(field=><Field key={field} title={{topic:'หัวข้อ Coaching',issue:'ปัญหาที่พบ',plan:'Action Plan',owner:'ผู้รับผิดชอบ',dueDate:'กำหนดส่ง',expectedResult:'ผลที่คาดหวัง',followUpNote:'บันทึกติดตาม'}[field]}>{field==='topic'?<select className={input} value={action.topic} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,topic:e.target.value}:a)})}><option value="">เลือกหัวข้อ</option>{form.topics.map(t=><option key={t}>{t}</option>)}</select>:<input className={input} type={field==='dueDate'?'date':'text'} value={action[field]} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,[field]:e.target.value}:a)})}/>}</Field>)}<Field title="สถานะ Action"><select className={input} value={action.status} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,status:e.target.value as CoachingAction['status']}:a)})}>{['Not Started','In Progress','Completed','Not Achieved'].map(s=><option key={s}>{s}</option>)}</select></Field><button className={button} disabled={!seniorEdit} onClick={()=>update({actions:form.actions.filter((_,j)=>i!==j)})}>ลบแผน</button></div>)}<button className={`${button} mt-3`} disabled={!seniorEdit} onClick={()=>update({actions:[...form.actions,{id:crypto.randomUUID(),topic:form.topics.find(t=>!form.actions.some(a=>a.topic===t))||form.topics[0]||'',issue:'',plan:'',owner:account.displayName||account.agentName,dueDate:'',expectedResult:'',followUpNote:'',status:'Not Started'}]})}>+ เพิ่ม Action Plan</button><textarea aria-label="เหตุผลที่ไม่ต้องทำ Action Plan" className={`${input} mt-3`} value={form.result.noPlanReason} disabled={!seniorEdit} onChange={e=>result({noPlanReason:e.target.value})} placeholder="เหตุผลที่ไม่ต้องทำ Action Plan (ถ้ามี)"/>
    </details>
    <section className={card}><h3 className="font-bold">QA Review</h3><textarea aria-label="QA Review Comment" className={`${input} mt-3`} value={form.review} disabled={!reviewEdit} onChange={e=>update({review:e.target.value})} placeholder="ระบุเหตุผลเมื่อส่งคืน Senior"/></section>
</main><aside className="mc-evidence">{evidence}<section className="mc-files"><h3>เอกสาร / ไฟล์ประกอบ (ถ้ามี)</h3>{form.attachments.map(a=><p key={a.path}><a href={/^https:\/\//i.test(a.url)?a.url:undefined} target="_blank" rel="noreferrer">{a.name}</a><small>{a.uploadedBy} • {new Date(a.uploadedAt).toLocaleString('en-GB',{timeZone:'Asia/Bangkok',hour12:false})}</small></p>)}<label className="mc-upload"><Icon kind="upload"/><span>เลือกไฟล์ประกอบ</span><input aria-label="แนบไฟล์ Coaching" type="file" accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg" disabled={!qaEdit&&!seniorEdit} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/><small>PDF, DOCX, XLSX, PNG, JPG · ไม่เกิน 3 MB ต่อไฟล์</small></label></section></aside>
    <div className="mc-actions"><div className="flex flex-wrap gap-2">{actions.filter(([,status])=>allowed.includes(status)).map(([title,status])=><button key={status} className={['Waiting Senior','Action Plan Submitted','Follow-up Next Month'].includes(status)?primary:button} disabled={busy||blocked} onClick={()=>void save(status)}>{busy?'กำลังบันทึก...':title}</button>)}</div>{!allowed.length&&<p className="text-sm text-slate-500">{record?.status==='Closed'||record?.status==='No Coaching Required'?'รายการนี้ปิดแล้ว แสดงข้อมูลเพื่อดูย้อนหลัง':'อยู่ระหว่างรออีกฝ่ายดำเนินการ'}</p>}{message&&<p role="status" className="text-sm text-violet-800">{message}</p>}</div>
  </div>;
}
