import React, { useEffect, useMemo, useState } from 'react';
import { fetchCanonicalCoachingEvaluations } from './coachingCanonicalStore';
import { getStoredEvaluationMonthKey, type StoredEvaluation } from './evaluationStore';
import { fetchStoredCoachingRecords, saveMonthlyCoachingRecord, type StoredCoachingRecord, type CoachingRecordStatus } from './coachingStore';
import { getRubricForDate } from './lib/rubricVersions';
import { scoreToGrade } from './lib/scoreIncentivePolicy';
import { uploadCoachingAttachment } from './coachingAttachmentUpload';
import { COACHING_WORKFLOW_START, HISTORICAL_COACHING_MONTHS, isHistoricalCoachingMonth, coachingDisplayStatus, coachingMonthLabel, initialCoachingMonth, allowedCoachingStatuses, belongsToAgent, COACHING_STATUSES, currentCoachingMonth, monthlyCoachingId, restoreCoachingForm, seniorFor, visibleCoachingAgents, coachingEndTime, followUpLabel, type CoachingAccount, type CoachingForm, type CoachingAction } from './monthlyCoachingModel';

type Props = { currentUser?: CoachingAccount | null; accounts: CoachingAccount[]; onOpenCase?: (caseId: string, agentName: string) => void };
const input = 'w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 focus:border-violet-500 focus:outline-none disabled:bg-slate-50';
const button = 'rounded-xl border border-violet-200 bg-white px-3 py-2 text-sm font-semibold text-violet-800 hover:bg-violet-50 disabled:cursor-not-allowed disabled:opacity-40';
const primary = 'rounded-xl bg-violet-700 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-800 disabled:cursor-not-allowed disabled:opacity-40';
const card = 'min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm';
const chip = 'inline-flex rounded-lg border border-violet-200 bg-violet-50 px-2 py-1 text-xs text-violet-800';
const readSession = (key: string) => { try { return JSON.parse(sessionStorage.getItem(key) || 'null'); } catch { return null; } };
const scoreOf = (rows: StoredEvaluation[]) => rows.length ? rows.reduce((sum, row) => sum + Number(row.finalScore || 0), 0) / rows.length : null;
const dateLabel = (date?: string) => date ? date.slice(0, 10).split('-').reverse().join('/') : '—';
const statusTone = (status?: string) => ['Coaching แล้ว', 'Closed', 'No Coaching Required', 'Follow-up Next Month'].includes(status || '') ? 'bg-emerald-50 text-emerald-700' : status === 'Action Plan Submitted' ? 'bg-sky-50 text-sky-700' : 'bg-amber-50 text-amber-800';
function Status({ value }: { value?: string }) { return <span className={`inline-flex rounded-lg px-2 py-1 text-xs font-semibold ${statusTone(value)}`}>{value || 'ยังไม่สร้าง'}</span>; }
function Field({ title, children }: { title: string; children: React.ReactNode }) { return <label className="block min-w-0 text-sm font-semibold text-slate-700"><span className="mb-1 block">{title}</span>{children}</label>; }
function topicPerformance(rows: StoredEvaluation[]) {
  const topics = new Map<string, { key: string; label: string; score: number; max: number; count: number; deductedCases: number; caseIds: string[] }>();
  rows.forEach(row => row.topics?.forEach(topic => {
    const key = `${topic.code}:${topic.title}`;
    const item = topics.get(key) || { key, label: topic.title, score: 0, max: 0, count: 0, deductedCases: 0, caseIds: [] };
    item.score += Number(topic.score || 0); item.max += Number(topic.max || 0); item.count++;
    if (Number(topic.score) < Number(topic.max)) { item.deductedCases++; if (row.caseId && !item.caseIds.includes(row.caseId)) item.caseIds.push(row.caseId); }
    topics.set(key, item);
  }));
  return [...topics.values()].map(t => ({ ...t, percentage: t.max ? t.score / t.max * 100 : 0, averageScore: t.score / t.count, maxScore: t.max / t.count }));
}

export default function MonthlyCoachingWorkspace({ currentUser, accounts, onOpenCase }: Props) {
  const qa = currentUser?.role === 'Quality Assurance';
  const viewKey = `qa-dashboard:monthly-coaching:view:${currentUser?.username}`;
  const [initialView] = useState(() => readSession(viewKey));
  const [month, setMonth] = useState<string>(() => initialCoachingMonth(initialView));
  const [selected, setSelected] = useState<string>(initialView?.selected || '');
  const [view, setView] = useState<'detail' | 'history' | 'scores'>(initialView?.view || 'detail');
  const [team, setTeam] = useState('all'); const [lead, setLead] = useState('all'); const [status, setStatus] = useState('all'); const [search, setSearch] = useState('');
  const [evaluations, setEvaluations] = useState<StoredEvaluation[]>([]); const [records, setRecords] = useState<StoredCoachingRecord[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reload, setReload] = useState(0); const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('');
  useEffect(() => { try { sessionStorage.setItem(viewKey, JSON.stringify({ periodVersion: 2, month, selected, view })); } catch { /* Form persistence reports its own errors. */ } }, [viewKey, month, selected, view]);
  useEffect(() => {
    let active = true; setLoading(true); setError('');
    Promise.all([fetchCanonicalCoachingEvaluations(), fetchStoredCoachingRecords({ allowCache: false })]).then(([rows, saved]) => { if (active) { setEvaluations(rows); setRecords(saved); } }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'โหลดข้อมูลไม่สำเร็จ'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [currentUser?.username, reload]);
  const agents = useMemo(() => visibleCoachingAgents(accounts, currentUser), [accounts, currentUser]);
  const teams = [...new Set(agents.map(a => a.teamName).filter(Boolean))]; const leads = [...new Set(agents.map(a => a.teamLead).filter(Boolean))];
  const account = agents.find(a => a.username === selected);
  const agentRecords = account ? records.filter(r => belongsToAgent(account, r.agentId, r.agent)).sort((a,b) => b.monthKey.localeCompare(a.monthKey) || b.updatedAt.localeCompare(a.updatedAt)) : [];
  const record = agentRecords.find(r => r.monthKey === month);
  const prior = agentRecords.find(r => r.monthKey < month);
  const agentRows = useMemo(() => account ? evaluations.filter(e => belongsToAgent(account, e.targetUsername, e.agentName)) : [], [evaluations, account]);
  const rows = useMemo(() => agentRows.filter(e => getStoredEvaluationMonthKey(e) === month), [agentRows, month]);
  const topics = useMemo(() => topicPerformance(rows), [rows]);
  const matchedAgents = agents.filter(a => (team === 'all' || a.teamName === team) && (lead === 'all' || a.teamLead === lead) && `${a.displayName} ${a.agentName} ${a.username}`.toLowerCase().includes(search.toLowerCase()));
  const recordFor = (a: CoachingAccount) => records.filter(r => r.monthKey === month && belongsToAgent(a, r.agentId, r.agent)).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt))[0];
  const historical = isHistoricalCoachingMonth(month);
  const displayStatus = (a: CoachingAccount) => coachingDisplayStatus(month, recordFor(a)?.status);
  const visible = matchedAgents.filter(a => status === 'all' || displayStatus(a) === status);
  const monthly = matchedAgents.map(recordFor).filter(Boolean) as StoredCoachingRecord[];
  const years = [...new Set([Number(month.slice(0,4)), 2026, Number(currentCoachingMonth().slice(0,4))+1, ...Array.from({length:Math.max(2,Number(currentCoachingMonth().slice(0,4))-2024)},(_,i)=>Number(currentCoachingMonth().slice(0,4))-i), ...records.map(r=>Number(r.monthKey.slice(0,4))), ...evaluations.map(e=>Number(getStoredEvaluationMonthKey(e).slice(0,4)))])].filter(y=>y>=2000).sort((a,b)=>b-a);
  const summary = historical ? [['Coaching ทั้งหมด', matchedAgents.length], ['Coaching แล้ว', matchedAgents.length], ['รอนัดหมาย', 0], ['รอ Senior', 0]] : [['Coaching ทั้งหมด', monthly.length], ['รอนัดหมาย', monthly.filter(r=>r.status==='Waiting Appointment').length], ['รอ Senior', monthly.filter(r=>r.status==='Waiting Senior').length], ['ส่งแผนแล้ว', monthly.filter(r=>r.status==='Action Plan Submitted').length], ['ปิดแล้ว', monthly.filter(r=>r.status==='Closed').length]];
  const setPeriod = (value: string) => { setMonth(value); setView('detail'); setNotice(''); };
  if (!currentUser) return null;
  return <div className="mx-auto max-w-[1800px] space-y-4 p-4 font-['Kanit'] text-slate-800">
    <header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-gradient-to-r from-teal-800 to-sky-800 p-5 text-white"><div><h1 className="text-2xl font-bold">Coaching รายบุคคล</h1><p className="text-sm">ผลประเมิน · นัดหมาย · แผนปรับปรุง</p></div><button className={button} disabled={busy || loading} onClick={()=>setReload(n=>n+1)}>โหลดข้อมูลล่าสุด</button></header>
    <div className={`${card} grid gap-3 sm:grid-cols-2 xl:grid-cols-7`}>
      <Field title="เดือน"><select aria-label="เดือน Coaching" className={input} value={month.slice(5)} disabled={busy} onChange={e=>setPeriod(`${month.slice(0,4)}-${e.target.value}`)}>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{coachingMonthLabel(`${month.slice(0,4)}-${String(i+1).padStart(2,'0')}`)}</option>)}</select></Field>
      <Field title="ปี ค.ศ."><select aria-label="ปี Coaching" className={input} value={month.slice(0,4)} disabled={busy} onChange={e=>setPeriod(`${e.target.value}-${month.slice(5)}`)}>{years.map(y=><option key={y}>{y}</option>)}</select></Field>
      <Field title="ทีม"><select className={input} value={team} disabled={!qa||busy} onChange={e=>setTeam(e.target.value)}><option value="all">{qa?'ทุกทีม':teams.join(', ')||'ทีมที่ดูแล'}</option>{teams.map(t=><option key={t}>{t}</option>)}</select></Field>
      <Field title="Senior"><select className={input} value={lead} disabled={!qa||busy} onChange={e=>setLead(e.target.value)}><option value="all">{qa?'ทุก Senior':currentUser.displayName}</option>{leads.map(t=><option key={t}>{t}</option>)}</select></Field>
      <Field title="สถานะ"><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทุกสถานะ</option>{['Coaching แล้ว', ...COACHING_STATUSES].map(s=><option key={s}>{s}</option>)}</select></Field>
      <div className="xl:col-span-2"><Field title="ค้นหา Admin"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="ชื่อ Admin" /></Field></div>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-900"><span>{historical ? 'มกราคม–สิงหาคม 2026: Coaching แล้ว · ประวัติก่อนเริ่มระบบใหม่' : month < COACHING_WORKFLOW_START ? 'ประวัติก่อนเริ่มระบบ Coaching ใหม่ · อ่านอย่างเดียว' : 'ระบบ Coaching ใหม่เริ่มกันยายน 2026 · มกราคม–สิงหาคม 2026 Coaching แล้ว'}</span><button className={button} disabled={busy} onClick={()=>{setPeriod(currentCoachingMonth());setStatus('all');}}>เดือนปัจจุบัน</button></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">โหลดข้อมูลไม่ครบ: {error} กรุณากดโหลดข้อมูลล่าสุดก่อนบันทึก</p>}
    {notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
    {loading ? <div role="status" className={card}>กำลังโหลดข้อมูล Coaching...</div> : <div className="grid items-start gap-4 lg:grid-cols-[280px_minmax(0,1fr)] 2xl:grid-cols-[290px_minmax(0,1fr)_280px]">
      <aside className={card}><div className="grid grid-cols-2 gap-2">{summary.map(([title,value])=><div key={title} className="rounded-xl bg-violet-50 p-2 text-xs">{title}<strong className="block text-xl text-violet-700">{value}</strong></div>)}</div><div className="mt-3 max-h-[70vh] space-y-2 overflow-y-auto">{visible.map(a=>{ const score=scoreOf(evaluations.filter(e=>getStoredEvaluationMonthKey(e)===month && belongsToAgent(a,e.targetUsername,e.agentName))); return <button type="button" key={a.username} disabled={busy} onClick={()=>{setSelected(a.username);setView('detail');setNotice('');}} className={`w-full rounded-xl border p-3 text-left text-sm ${a.username===selected?'border-violet-500 bg-violet-50':'border-slate-100 hover:bg-slate-50'}`}><strong className="block break-words">{a.displayName||a.agentName}</strong><span className={`mr-2 font-semibold ${score!==null && score>=85?'text-emerald-600':'text-red-600'}`}>{score===null?'ยังไม่มีคะแนน':`${score.toFixed(1)}%`}</span><Status value={displayStatus(a)} /></button>;})}{!visible.length && <p className="p-3 text-sm text-slate-500">ไม่พบ Admin ตามทีมและตัวกรองที่เลือก</p>}</div></aside>
      <main className="min-w-0 space-y-4">{account ? <>
        <section className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="break-words text-xl font-bold">{account.displayName||account.agentName}</h2><p className="text-sm">{record?.team||account.teamName||'ยังไม่มีทีม'} · Senior: {record?.seniorName||record?.coachedBy||account.teamLead||'ยังไม่ระบุ'}</p><p className="mt-1 text-sm">{coachingMonthLabel(month)} · {rows.length} เคส · Critical Error {rows.filter(e=>e.criticalError).length}</p></div><div className="text-right"><strong className={`block text-2xl ${scoreOf(rows)!>=85?'text-emerald-600':'text-red-600'}`}>{scoreOf(rows)===null?'—':`${scoreOf(rows)!.toFixed(1)}%`}</strong><span className="block text-xs">{scoreOf(rows)===null?'ยังไม่มีผลประเมิน':scoreOf(rows)!>=85?'Passed':'Not Passed'}</span><Status value={coachingDisplayStatus(month,record?.status)} /></div></div><div className="mt-3 flex flex-wrap gap-2">{([['detail','ข้อมูล Coaching'],['history','ประวัติ Coaching'],['scores','ประวัติคะแนน']] as const).map(([key,title])=><button key={key} className={view===key?primary:button} disabled={busy} onClick={()=>setView(key)}>{title}</button>)}</div></section>
        {view==='detail' ? month < COACHING_WORKFLOW_START ? <ArchivedCoaching month={month} record={record} /> : <CoachingDetail key={`${currentUser.username}:${account.username}:${month}:${record?.updatedAt||'new'}`} currentUser={currentUser} accounts={accounts} account={account} month={month} record={record} prior={prior} rows={rows} topics={topics} blocked={Boolean(error)} onBusy={setBusy} onSaved={saved=>{setRecords(rs=>[saved,...rs.filter(r=>r.id!==saved.id)]);setNotice(`บันทึกแล้ว · ${saved.status}`);}} /> : view==='history' ? <section className={card}><h3 className="font-bold">ประวัติ Coaching</h3>{[...new Set([...HISTORICAL_COACHING_MONTHS,...agentRecords.map(r=>r.monthKey)])].sort().reverse().map(m=>{const r=agentRecords.find(row=>row.monthKey===m);return <button key={m} disabled={busy} className="mt-3 block w-full rounded-xl border p-3 text-left text-sm" onClick={()=>setPeriod(m)}><strong>{coachingMonthLabel(m)}</strong> <Status value={coachingDisplayStatus(m,r?.status)}/>{isHistoricalCoachingMonth(m)&&<span className="block text-slate-500">ประวัติก่อนเริ่มระบบใหม่</span>}{r&&<><span className="block">Senior: {r.seniorName||r.coachedBy||'—'} · ทีม {r.team||'—'}</span><span className="block">{r.qaSummary||r.mainIssues}</span>{(r.actions||[]).map(a=><span key={a.id} className="mt-1 block">{a.topic}: {a.plan} · {dateLabel(a.dueDate)} · {a.status}</span>)}</>}</button>;})}</section> : <section className={card}><h3 className="font-bold">ประวัติคะแนน</h3>{[...new Set(agentRows.map(getStoredEvaluationMonthKey))].sort().map((m,i,months)=>{const cases=agentRows.filter(e=>getStoredEvaluationMonthKey(e)===m);const current=topicPerformance(cases);const previous=topicPerformance(agentRows.filter(e=>getStoredEvaluationMonthKey(e)===months[i-1]));return <div key={m} className="border-b py-3"><strong>{m} · {scoreOf(cases)?.toFixed(1)}% · {cases.length} เคส</strong><div className="mt-2 flex flex-wrap gap-2">{current.map(t=>{const old=previous.find(p=>p.key===t.key);const delta=old?t.percentage-old.percentage:null;return <span key={t.key} className={chip}>{t.label} {t.percentage.toFixed(1)}% {delta===null?'':delta>0.5?'↑ ดีขึ้น':delta<-.5?'↓ ลดลง':'= เท่าเดิม'}</span>;})}</div></div>;})}</section>}
      </> : <section className={card}>เลือก Admin เพื่อดู Coaching รายบุคคล</section>}</main>
      <aside className={`${card} lg:col-start-2 2xl:col-start-auto`}><h3 className="font-bold">คะแนนรายหัวข้อ</h3>{topics.map(t=><div key={t.key} className="mt-3 border-b pb-3 text-sm"><strong className="block break-words">{t.label}</strong><div className="my-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full ${t.percentage>=85?'bg-emerald-500':'bg-amber-500'}`} style={{width:`${Math.max(0,Math.min(100,t.percentage))}%`}} /></div><p>{t.averageScore.toFixed(1)} / {t.maxScore.toFixed(1)} · {t.percentage.toFixed(1)}%</p><p>ถูกหัก {t.deductedCases} เคส</p>{t.caseIds.map(id=><button key={id} className="mr-2 mt-1 text-violet-700 underline" disabled={busy} onClick={()=>onOpenCase?.(id,account?.agentName||account?.displayName||'')}>{id}</button>)}</div>)}{!topics.length && <p className="mt-2 text-sm text-slate-500">ยังไม่มีคะแนนเดือนนี้</p>}<h3 className="mt-4 font-bold text-red-700">Critical Error</h3>{rows.filter(e=>e.criticalError).map(e=><button key={e.id} className="mt-2 block text-sm text-red-700 underline" onClick={()=>onOpenCase?.(e.caseId,account?.agentName||'')}>{e.caseId}</button>)}<p className="text-sm">{rows.filter(e=>e.criticalError).length} เคส</p></aside>
    </div>}
  </div>;
}

function ArchivedCoaching({month,record}: {month:string;record?:StoredCoachingRecord}) {
  return <section className={card}><h3 className="text-lg font-bold">{coachingMonthLabel(month)} · {isHistoricalCoachingMonth(month)?'Coaching แล้ว':'ประวัติ Coaching'}</h3><p className="mt-2 text-sm text-slate-600">ระบบใหม่เริ่มกันยายน 2026 ไม่ต้องกรอกนัดหมายหรือ Action Plan ย้อนหลัง</p>{record ? <div className="mt-4 space-y-3 whitespace-pre-wrap text-sm"><p>{record.qaSummary||record.generalFeedback||record.mainIssues}</p><p>{record.actualCoaching?.finalNote||record.additionalNote}</p><p>{record.actionPlan||record.agreedActionPlan}</p>{record.actions?.map(a=><p key={a.id}>{a.topic}: {a.plan} · {dateLabel(a.dueDate)}</p>)}{record.attachments?.map(a=><a key={a.path} className="block text-violet-700 underline" href={/^https:\/\//i.test(a.url)?a.url:undefined} target="_blank" rel="noreferrer">{a.name}</a>)}</div> : <p className="mt-4 text-sm text-slate-500">ไม่มีรายละเอียดบันทึกย้อนหลังในระบบ</p>}</section>;
}

type DetailProps = { currentUser: CoachingAccount; accounts: CoachingAccount[]; account: CoachingAccount; month: string; record?: StoredCoachingRecord; prior?: StoredCoachingRecord; rows: StoredEvaluation[]; topics: ReturnType<typeof topicPerformance>; blocked: boolean; onBusy: (busy:boolean)=>void; onSaved: (record:StoredCoachingRecord)=>void };
function CoachingDetail({currentUser,accounts,account,month,record,prior,rows,topics,blocked,onBusy,onSaved}: DetailProps) {
  const formKey = `qa-dashboard:monthly-coaching:editing:${currentUser.username}:${account.username}:${month}`;
  const [form,setForm]=useState<CoachingForm>(()=>restoreCoachingForm(record,readSession(formKey),currentUser.role));
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const allowed=allowedCoachingStatuses(currentUser.role,record); const qa=currentUser.role==='Quality Assurance';
  const qaEdit=qa&&allowed.includes('Draft')&&!busy&&!blocked; const seniorEdit=!qa&&allowed.includes('Coaching In Progress')&&!busy&&!blocked; const reviewEdit=qa&&allowed.includes('QA Reviewed')&&!busy&&!blocked;
  const availableTopics=[...new Set([...getRubricForDate(`${month}-01`).topics.map(t=>t.title),...topics.map(t=>t.label),...form.topics])];
  const followUp=topics.map(t=>({...t,result:followUpLabel(t,prior?.topicSnapshot.find(p=>p.label===t.label),prior?.recommendedTopics?.includes(t.label)||prior?.actions?.some(a=>a.topic===t.label))}));
  const update=(patch:Partial<CoachingForm>)=>{const next={...form,...patch};setForm(next);try{sessionStorage.setItem(formKey,JSON.stringify(next));}catch{setMessage('เบราว์เซอร์เก็บข้อความชั่วคราวไม่สำเร็จ กรุณาบันทึกก่อนออกจากหน้า');}};
  const appointment=(patch:Partial<CoachingForm['appointment']>)=>update({appointment:{...form.appointment,...patch}});
  const result=(patch:Partial<CoachingForm['result']>)=>update({result:{...form.result,...patch}});
  const pending=(value:boolean)=>{setBusy(value);onBusy(value);};
  const save=async(status:CoachingRecordStatus)=>{
    if(blocked||busy||!allowed.includes(status))return;
    pending(true);setMessage('');
    try{
      const now=new Date().toISOString();const average=scoreOf(rows);const owner=seniorFor(accounts,account);
      const candidate:StoredCoachingRecord={...record,id:record?.id||monthlyCoachingId(account.username,month),agentId:record?.agentId||account.username,agent:record?.agent||account.agentName||account.displayName,team:record?.team||account.teamName||'',teamId:record?.teamId||account.teamName||'',seniorId:record?.seniorId||owner?.username||'',seniorName:record?.seniorName||record?.coachedBy||account.teamLead||'',monthKey:month,monthLabel:month,coachingDate:form.result.date||record?.coachingDate||'',coachedBy:record?.coachedBy||account.teamLead||'',evaluatedCases:rows.length,averageScore:average??record?.averageScore??0,grade:average===null?record?.grade||'':scoreToGrade(average,month),criticalErrors:rows.filter(e=>e.criticalError).length,strengths:record?.strengths||'',mainIssues:record?.mainIssues||'',repeatedIssues:record?.repeatedIssues||'',coachingRecommendation:record?.coachingRecommendation||'',actionPlan:record?.actionPlan||'',followUpDate:record?.followUpDate||'',result:record?.result||'Pending Review',status,caseReferences:rows.map(e=>e.caseId).filter(Boolean),topicSnapshot:topics.map(t=>({key:t.key,label:t.label,averageScore:t.averageScore,maxScore:t.maxScore,percentage:t.percentage,deductedCases:t.deductedCases,caseIds:t.caseIds})),checklistItems:record?.checklistItems||[],generalFeedback:record?.generalFeedback||'',agentResponse:record?.agentResponse||'',agreedActionPlan:record?.agreedActionPlan||'',additionalNote:record?.additionalNote||'',qaSummary:form.summary,recommendedTopics:form.topics,appointment:{...form.appointment,participants:[...new Set([account.displayName||account.agentName,record?.seniorName||account.teamLead||'',...form.appointment.participants].filter(Boolean))]},actualCoaching:form.result,actions:form.actions,qaReviewComment:form.review,attachments:form.attachments,createdAt:record?.createdAt||now,updatedAt:now};
      const saved=await saveMonthlyCoachingRecord(candidate,currentUser,accounts,record?.updatedAt??null);
      sessionStorage.removeItem(formKey);onSaved(saved);
    }catch(e){setMessage(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{pending(false);}
  };
  const upload=async(file?:File)=>{if(!file||(!qaEdit&&!seniorEdit))return;pending(true);try{const attachment=await uploadCoachingAttachment(file,record?.id||monthlyCoachingId(account.username,month),currentUser.displayName);update({attachments:[...form.attachments,attachment]});setMessage('ไฟล์อัปโหลดแล้ว กรุณากดบันทึกเพื่อเชื่อมกับ Coaching');}catch(e){setMessage(e instanceof Error?e.message:'อัปโหลดไม่สำเร็จ');}finally{pending(false);}};
  const actions:[string,CoachingRecordStatus][] = qa ? [['บันทึก Draft','Draft'],['รอนัดหมาย','Waiting Appointment'],['นัดหมาย','Appointment Scheduled'],['ส่งให้ Senior','Waiting Senior'],['รับแผน','Follow-up Next Month'],['ส่งคืน Senior','QA Reviewed'],['ไม่ต้อง Coaching','No Coaching Required'],['ปิดเคส','Closed']] : [['บันทึกผล','Coaching In Progress'],['ส่ง Action Plan ให้ QA','Action Plan Submitted']];
  return <>
    {prior&&<section className={card}><h3 className="font-bold">Coaching ล่าสุด · {prior.monthKey}</h3><p className="mt-2 whitespace-pre-wrap text-sm">{prior.qaSummary||prior.mainIssues||prior.generalFeedback}</p><p className="mt-2 text-sm">{(prior.recommendedTopics||[]).join(', ')}</p>{(prior.actions||[]).map(a=><div key={a.id} className="mt-2 rounded-xl bg-slate-50 p-3 text-sm"><strong>{a.topic}</strong><p>{a.plan}</p><p>กำหนด {dateLabel(a.dueDate)} · {a.status}</p></div>)}{prior.actualCoaching?.finalNote&&<p className="mt-2 whitespace-pre-wrap text-sm">Senior Note: {prior.actualCoaching.finalNote}</p>}<div className="mt-3 flex flex-wrap gap-2">{followUp.filter(t=>t.result).map(t=><span key={t.key} className={chip}>{t.label}: {t.result}</span>)}</div></section>}
    <details className={card} open><summary className="cursor-pointer font-bold">QA Summary และหัวข้อที่แนะนำ</summary><textarea aria-label="QA Summary" className={`${input} mt-3 min-h-32`} value={form.summary} readOnly={!qaEdit} onChange={e=>update({summary:e.target.value})} placeholder="สรุปผลของ Admin รายบุคคล"/><div className="mt-3 flex flex-wrap gap-2">{availableTopics.map(t=><label key={t} className={`${chip} items-start gap-2`}><input type="checkbox" checked={form.topics.includes(t)} disabled={!qaEdit} onChange={e=>update({topics:e.target.checked?[...form.topics,t]:form.topics.filter(x=>x!==t)})}/><span>{t}{topics.some(p=>p.label===t&&p.deductedCases)?' · แนะนำ':''}{followUp.find(p=>p.label===t)?.result?` · ${followUp.find(p=>p.label===t)?.result}`:''}</span></label>)}</div></details>
    <details className={card} open={qa}><summary className="cursor-pointer font-bold">นัดหมาย Coaching และ Agenda</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field title="วันที่นัดหมาย"><input type="date" className={input} value={form.appointment.date} disabled={!qaEdit} onChange={e=>appointment({date:e.target.value})}/></Field><Field title="เวลาเริ่ม (24 ชั่วโมง)"><input type="time" className={input} value={form.appointment.startTime} disabled={!qaEdit} onChange={e=>appointment({startTime:e.target.value})}/></Field><Field title="ระยะเวลา (นาที)"><input type="number" min="1" max="1440" className={input} value={form.appointment.duration} disabled={!qaEdit} onChange={e=>appointment({duration:Number(e.target.value)})}/></Field><Field title="ช่องทาง"><select className={input} value={form.appointment.method} disabled={!qaEdit} onChange={e=>appointment({method:e.target.value})}><option>Face to Face</option><option>MS Teams</option><option>Other</option></select></Field></div><p className="mt-2 text-sm">เวลาสิ้นสุด {coachingEndTime(form.appointment.startTime,form.appointment.duration)||'—'}</p><p className="text-sm">ผู้เข้าร่วม: {account.displayName||account.agentName} · {record?.seniorName||account.teamLead||'ยังไม่ระบุ Senior'}</p>
      {form.appointment.method==='MS Teams'&&<input aria-label="MS Teams URL" className={`${input} mt-2`} type="url" placeholder="https://teams.microsoft.com/..." value={form.appointment.url} disabled={!qaEdit} onChange={e=>appointment({url:e.target.value})}/>}{form.appointment.method==='Other'&&<input aria-label="รายละเอียดช่องทาง" className={`${input} mt-2`} value={form.appointment.other} disabled={!qaEdit} onChange={e=>appointment({other:e.target.value})}/>}
      <div className="mt-3"><Field title="ผู้เข้าร่วมเพิ่มเติม"><input className={input} value={form.appointment.participants.join(', ')} disabled={!qaEdit} onChange={e=>appointment({participants:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})} placeholder="คั่นชื่อด้วย ,"/></Field></div><h4 className="mt-3 font-semibold">Agenda / แพลนที่จะคุย</h4><button className={`${button} mt-2`} disabled={!qaEdit||!form.topics.length} onClick={()=>appointment({agenda:[...new Set([...form.appointment.agenda.filter(x=>x.trim()),...form.topics.map(t=>`ทบทวน ${t}`)])]})}>เพิ่ม Agenda จากหัวข้อที่เลือก</button>{form.appointment.agenda.map((text,i)=><div key={i} className="mt-2 flex items-center gap-2"><span>{i+1}.</span><input aria-label={`Agenda ${i+1}`} className={input} value={text} disabled={!qaEdit} onChange={e=>appointment({agenda:form.appointment.agenda.map((x,j)=>i===j?e.target.value:x)})}/><button aria-label={`ลบ Agenda ${i+1}`} className={button} disabled={!qaEdit} onClick={()=>appointment({agenda:form.appointment.agenda.filter((_,j)=>i!==j)})}>ลบ</button></div>)}<button className={`${button} mt-2`} disabled={!qaEdit} onClick={()=>appointment({agenda:[...form.appointment.agenda,'']})}>+ เพิ่ม Agenda</button><textarea aria-label="หมายเหตุนัดหมาย" className={`${input} mt-3`} value={form.appointment.note} disabled={!qaEdit} onChange={e=>appointment({note:e.target.value})} placeholder="หมายเหตุนัดหมาย"/>
    </details>
    <details className={card} open={!qa}><summary className="cursor-pointer font-bold">ผล Coaching และ Action Plan โดย Senior</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field title="วันที่ Coaching จริง"><input type="date" className={input} value={form.result.date} disabled={!seniorEdit} onChange={e=>result({date:e.target.value})}/></Field><Field title="เวลาเริ่มจริง"><input type="time" className={input} value={form.result.startTime} disabled={!seniorEdit} onChange={e=>result({startTime:e.target.value})}/></Field><Field title="เวลาสิ้นสุดจริง"><input type="time" className={input} value={form.result.endTime} disabled={!seniorEdit} onChange={e=>result({endTime:e.target.value})}/></Field></div><h4 className="mt-3 text-sm font-semibold">หัวข้อที่คุยจริง</h4><div className="mt-2 flex flex-wrap gap-2">{form.topics.map(t=><label key={t} className={`${chip} gap-2`}><input type="checkbox" checked={form.result.topics.includes(t)} disabled={!seniorEdit} onChange={e=>result({topics:e.target.checked?[...form.result.topics,t]:form.result.topics.filter(x=>x!==t)})}/>{t}</label>)}</div><textarea aria-label="Senior Coaching Note" className={`${input} mt-3`} value={form.result.note} disabled={!seniorEdit} onChange={e=>result({note:e.target.value})} placeholder="Senior Coaching Note"/><textarea aria-label="Senior Final Note" className={`${input} mt-3`} value={form.result.finalNote} disabled={!seniorEdit} onChange={e=>result({finalNote:e.target.value})} placeholder="Senior Final Note"/>
      <h4 className="mt-3 font-semibold">Action Plan รายหัวข้อ</h4>{form.actions.map((action,i)=><div key={action.id} className="mt-3 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 sm:grid-cols-2">{(['topic','issue','plan','owner','dueDate','expectedResult','followUpNote'] as const).map(field=><Field key={field} title={{topic:'หัวข้อ Coaching',issue:'ปัญหาที่พบ',plan:'Action Plan',owner:'ผู้รับผิดชอบ',dueDate:'กำหนดส่ง',expectedResult:'ผลที่คาดหวัง',followUpNote:'บันทึกติดตาม'}[field]}>{field==='topic'?<select className={input} value={action.topic} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,topic:e.target.value}:a)})}><option value="">เลือกหัวข้อ</option>{form.topics.map(t=><option key={t}>{t}</option>)}</select>:<input className={input} type={field==='dueDate'?'date':'text'} value={action[field]} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,[field]:e.target.value}:a)})}/>}</Field>)}<Field title="สถานะ Action"><select className={input} value={action.status} disabled={!seniorEdit} onChange={e=>update({actions:form.actions.map((a,j)=>i===j?{...a,status:e.target.value as CoachingAction['status']}:a)})}>{['Not Started','In Progress','Completed','Not Achieved'].map(s=><option key={s}>{s}</option>)}</select></Field><button className={button} disabled={!seniorEdit} onClick={()=>update({actions:form.actions.filter((_,j)=>i!==j)})}>ลบแผน</button></div>)}<button className={`${button} mt-3`} disabled={!seniorEdit} onClick={()=>update({actions:[...form.actions,{id:crypto.randomUUID(),topic:form.topics.find(t=>!form.actions.some(a=>a.topic===t))||form.topics[0]||'',issue:'',plan:'',owner:account.displayName||account.agentName,dueDate:'',expectedResult:'',followUpNote:'',status:'Not Started'}]})}>+ เพิ่ม Action Plan</button><textarea aria-label="เหตุผลที่ไม่ต้องทำ Action Plan" className={`${input} mt-3`} value={form.result.noPlanReason} disabled={!seniorEdit} onChange={e=>result({noPlanReason:e.target.value})} placeholder="เหตุผลที่ไม่ต้องทำ Action Plan (ถ้ามี)"/>
    </details>
    <section className={card}><h3 className="font-bold">QA Review</h3><textarea aria-label="QA Review Comment" className={`${input} mt-3`} value={form.review} disabled={!reviewEdit} onChange={e=>update({review:e.target.value})} placeholder="ระบุเหตุผลเมื่อส่งคืน Senior"/></section>
    <details className={card} open={form.attachments.length>0}><summary className="cursor-pointer font-bold">ไฟล์ประกอบ ({form.attachments.length})</summary>{form.attachments.map(a=><p key={a.path} className="mt-2 break-words text-sm"><a href={/^https:\/\//i.test(a.url)?a.url:undefined} target="_blank" rel="noreferrer" className="text-violet-700 underline">{a.name}</a><span className="block text-xs text-slate-500">{a.uploadedBy} · {new Date(a.uploadedAt).toLocaleString('en-GB',{timeZone:'Asia/Bangkok',hour12:false})}</span></p>)}<input aria-label="แนบไฟล์ Coaching" className="mt-3 max-w-full text-sm" type="file" accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg" disabled={!qaEdit&&!seniorEdit} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/><p className="mt-2 text-xs text-slate-500">PDF, DOCX, XLSX, PNG, JPG · ไม่เกิน 3 MB ต่อไฟล์</p></details>
    <div className={`${card} sticky bottom-2 z-10 space-y-2`}><div className="flex flex-wrap gap-2">{actions.filter(([,status])=>allowed.includes(status)).map(([title,status])=><button key={status} className={['Waiting Senior','Action Plan Submitted','Follow-up Next Month'].includes(status)?primary:button} disabled={busy||blocked} onClick={()=>void save(status)}>{busy?'กำลังบันทึก...':title}</button>)}</div>{!allowed.length&&<p className="text-sm text-slate-500">{record?.status==='Closed'||record?.status==='No Coaching Required'?'รายการนี้ปิดแล้ว แสดงข้อมูลเพื่อดูย้อนหลัง':'อยู่ระหว่างรออีกฝ่ายดำเนินการ'}</p>}{message&&<p role="status" className="text-sm text-violet-800">{message}</p>}</div>
  </>;
}
