export const THT_PLUS_2026_PRETEST_SET = {
  id: "tht-plus-2026-30q-slide-notes",
  code: "PRE-THT-PLUS-2026-30Q",
  title: "Pre-Test: ไทยช่วยไทย พลัส 2026 / THT Plus",
  description: "แบบทดสอบ 30 ข้อจากไฟล์ THT Plus 2026 พร้อมหมายเหตุอ้างอิง Slide สำหรับหน้า Question Sets",
  passScore: 24,
  timeLimitSeconds: 1800,
  active: true,
  updatedAt: "2026-06-18T17:16:31+07:00",
  updatedBy: "System",
  questions: [
    {
      id: "tht-plus-2026-q01",
      prompt: "ออเดอร์โครงการไทยช่วยไทย พลัส ที่ต้อง Monitor ใน Admin Panel V.2 คือสถานะใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "จัดส่งสำเร็จ" },
        { id: "B", text: "รอรับงาน" },
        { id: "C", text: "ยกเลิกแล้ว" },
        { id: "D", text: "กำลังคืนเงิน" },
      ],
    },
    {
      id: "tht-plus-2026-q02",
      prompt: "เมื่อพบออเดอร์สถานะ “รอรับงาน” ขั้นตอนแรกควรทำอะไร",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ยกเลิกออเดอร์ทันที" },
        { id: "B", text: "ค้นหาไรเดอร์ที่อยู่ใกล้ตำแหน่งร้านค้า" },
        { id: "C", text: "ส่งต่อ IT Service ทันที" },
        { id: "D", text: "แจ้งลูกค้าว่าไม่สามารถจัดส่งได้" },
      ],
    },
    {
      id: "tht-plus-2026-q03",
      prompt: "หากยังไม่พบไรเดอร์ ต้อง Monitor พื้นที่บริเวณร้านค้าภายในเวลากี่นาที",
      correctChoiceId: "C",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "10 นาที" },
        { id: "B", text: "15 นาที" },
        { id: "C", text: "30 นาที" },
        { id: "D", text: "60 นาที" },
      ],
    },
    {
      id: "tht-plus-2026-q04",
      prompt: "หากพบไรเดอร์พร้อมรับงานในระบบ ควรดำเนินการอย่างไรใน Admin Panel V.2",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ระบุ Rider ID ของไรเดอร์ที่พร้อมรับงาน" },
        { id: "B", text: "ระบุเลข Order ID ของลูกค้า" },
        { id: "C", text: "ปิดเคสทันที" },
        { id: "D", text: "ส่งต่อให้ร้านค้าจัดการเอง" },
      ],
    },
    {
      id: "tht-plus-2026-q05",
      prompt: "เมนูที่ใช้ระบุไรเดอร์ใน Admin Panel V.2 คือเมนูใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ค้นหาออเดอร์" },
        { id: "B", text: "ค้นหาไรเดอร์" },
        { id: "C", text: "ตรวจสอบสถานะ" },
        { id: "D", text: "คืนเงินลูกค้า" },
      ],
    },
    {
      id: "tht-plus-2026-q06",
      prompt: "กรณียังหาไรเดอร์ไม่ได้ ต้องระบุ Rider ID ประเภทใดก่อน",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "Rider VIP" },
        { id: "B", text: "Rider Dummy" },
        { id: "C", text: "Rider Cancel" },
        { id: "D", text: "Rider Refund" },
      ],
    },
    {
      id: "tht-plus-2026-q07",
      prompt: "หลังระบุ Rider ID แล้ว ต้องกดปุ่มใดเพื่อยืนยัน",
      correctChoiceId: "C",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "Save" },
        { id: "B", text: "Submit" },
        { id: "C", text: "Enter" },
        { id: "D", text: "Complete" },
      ],
    },
    {
      id: "tht-plus-2026-q08",
      prompt: "หากไม่พบไรเดอร์ในระบบหลัง Monitor แล้ว ควรใช้ช่องทางใดในการค้นหาไรเดอร์เพิ่มเติม",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "Lalamove" },
        { id: "B", text: "Facebook" },
        { id: "C", text: "Email" },
        { id: "D", text: "Call Center ธนาคาร" },
      ],
    },
    {
      id: "tht-plus-2026-q09",
      prompt: "เมื่อติดต่อไรเดอร์ผ่าน Lalamove ต้องย้ำเรื่องใดกับไรเดอร์",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ให้รีบกดรับงานโดยไม่ต้องถ่ายรูป" },
        { id: "B", text: "ให้ถ่ายภาพรับ-ส่งให้เห็นอาหารชัดเจน" },
        { id: "C", text: "ให้โทรหาร้านค้าหลังจบงานเท่านั้น" },
        { id: "D", text: "ให้ยกเลิกงานหลังรับอาหาร" },
      ],
    },
    {
      id: "tht-plus-2026-q10",
      prompt: "หลังจัดส่งสำเร็จ กรณีมีการใช้ Rider Dummy ต้องดำเนินการอย่างไร",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ลบ Order ID ออกจากระบบ" },
        { id: "B", text: "ยกเลิกงานของ Rider Dummy ใน OPS Portal" },
        { id: "C", text: "คืนเงินให้ลูกค้าทันที" },
        { id: "D", text: "ปิดร้านค้าในระบบ" },
      ],
    },
    {
      id: "tht-plus-2026-q11",
      prompt: "หลังจัดส่งสำเร็จและต้องปรับสถานะออเดอร์เป็น Complete ต้องบันทึกเคสหัวข้อใด",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "ปรับสถานะออเดอร์เป็น Complete" },
        { id: "B", text: "แจ้งปัญหาอาหารเสียหาย" },
        { id: "C", text: "แจ้งยกเลิกออเดอร์" },
        { id: "D", text: "แจ้งลูกค้าไม่ได้ชำระเงิน" },
      ],
    },
    {
      id: "tht-plus-2026-q12",
      prompt: "เคส “ปรับสถานะออเดอร์เป็น Complete” มี SLA เท่าใด",
      correctChoiceId: "C",
      slideNote: "อ้างอิง Slide 2",
      choices: [
        { id: "A", text: "30 นาที" },
        { id: "B", text: "2 ชั่วโมง" },
        { id: "C", text: "1 วันทำการ" },
        { id: "D", text: "3 วันทำการ" },
      ],
    },
    {
      id: "tht-plus-2026-q13",
      prompt: "ในระบบ Lalamove ต้องเลือกเมนูใดเพื่อเรียกไรเดอร์",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "เรียกงานส่งของ" },
        { id: "B", text: "ตรวจสอบยอดเงิน" },
        { id: "C", text: "ค้นหา Rider Dummy" },
        { id: "D", text: "ปิดงานจัดส่ง" },
      ],
    },
    {
      id: "tht-plus-2026-q14",
      prompt: "จุดรับสินค้าใน Lalamove ต้องกรอกข้อมูลใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "ที่อยู่ลูกค้าและเบอร์ลูกค้า" },
        { id: "B", text: "ที่ตั้งและเบอร์โทรศัพท์ร้านค้า" },
        { id: "C", text: "ชื่อไรเดอร์และเบอร์ไรเดอร์" },
        { id: "D", text: "เลขเคสและชื่อแอดมิน" },
      ],
    },
    {
      id: "tht-plus-2026-q15",
      prompt: "จุดส่งสินค้าใน Lalamove ต้องใช้ข้อมูลจากที่ใด",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "ตำแหน่งที่ลูกค้าปักหมุดไว้ในระบบ" },
        { id: "B", text: "ที่อยู่ร้านค้า" },
        { id: "C", text: "ที่อยู่สำนักงาน" },
        { id: "D", text: "ที่อยู่ของไรเดอร์" },
      ],
    },
    {
      id: "tht-plus-2026-q16",
      prompt: "ประเภทรถที่ต้องเลือกใน Lalamove คือข้อใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "รถยนต์" },
        { id: "B", text: "มอเตอร์ไซค์" },
        { id: "C", text: "รถกระบะ" },
        { id: "D", text: "รถแท็กซี่" },
      ],
    },
    {
      id: "tht-plus-2026-q17",
      prompt: "บริการเสริมที่ต้องเลือกใน Lalamove คือข้อใด",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "กล่องบรรจุอาหาร" },
        { id: "B", text: "ประกันสินค้า" },
        { id: "C", text: "ส่งด่วนพิเศษ" },
        { id: "D", text: "เก็บเงินปลายทาง" },
      ],
    },
    {
      id: "tht-plus-2026-q18",
      prompt: "รูปแบบราคาที่ต้องเลือกใน Lalamove คือข้อใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "ราคาพิเศษ" },
        { id: "B", text: "ราคาปกติ" },
        { id: "C", text: "ราคาส่วนลด" },
        { id: "D", text: "ราคาเหมาจ่าย" },
      ],
    },
    {
      id: "tht-plus-2026-q19",
      prompt: "ช่องทางการชำระเงินใน Lalamove ต้องเลือกเป็นอะไร",
      correctChoiceId: "C",
      slideNote: "อ้างอิง Slide 3",
      choices: [
        { id: "A", text: "เงินสด" },
        { id: "B", text: "บัตรเครดิต" },
        { id: "C", text: "Wallet" },
        { id: "D", text: "โอนธนาคาร" },
      ],
    },
    {
      id: "tht-plus-2026-q20",
      prompt: "กรณีลูกค้าแจ้งได้รับอาหารไม่ครบ/ผิดเมนู ข้อมูลที่ต้องสอบถามคือข้อใด",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 5",
      choices: [
        { id: "A", text: "Order ID, เบอร์โทรศัพท์ถ้ามี, รูปถ่ายอาหารที่ได้รับทั้งหมด" },
        { id: "B", text: "ชื่อไรเดอร์, สีรถ, ทะเบียนรถ" },
        { id: "C", text: "เลขบัญชีธนาคาร, ชื่อธนาคาร" },
        { id: "D", text: "ชื่อร้านค้าอย่างเดียว" },
      ],
    },
    {
      id: "tht-plus-2026-q21",
      prompt: "เมื่อลูกค้าแจ้งอาหารไม่ครบ ต้องตรวจสอบอะไรเป็นหลัก",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 5",
      choices: [
        { id: "A", text: "ตรวจสอบรูปถ่ายอาหารว่าได้รับครบตามจำนวนที่สั่งหรือไม่" },
        { id: "B", text: "ตรวจสอบยอดเงินเดือนของไรเดอร์" },
        { id: "C", text: "ตรวจสอบตำแหน่ง GPS ของร้านค้าอย่างเดียว" },
        { id: "D", text: "ตรวจสอบโปรโมชั่นในระบบ" },
      ],
    },
    {
      id: "tht-plus-2026-q22",
      prompt: "หากลูกค้าไม่ให้ข้อมูลเพิ่มเติม และข้อมูลไม่ครบ ควรแจ้งอย่างไร",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 5",
      choices: [
        { id: "A", text: "“เนื่องจากข้อมูลไม่ครบถ้วน จึงไม่สามารถตรวจสอบได้ค่ะ”" },
        { id: "B", text: "“ระบบจะคืนเงินให้ทันทีทุกกรณีค่ะ”" },
        { id: "C", text: "“ร้านค้าต้องรับผิดชอบทั้งหมดค่ะ”" },
        { id: "D", text: "“ไรเดอร์ผิดทุกกรณีค่ะ”" },
      ],
    },
    {
      id: "tht-plus-2026-q23",
      prompt: "หากตรวจสอบแล้วพบว่าอาหารครบตามจำนวนที่สั่ง ควรแจ้งลูกค้าอย่างไร",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 5",
      choices: [
        { id: "A", text: "แจ้งว่าระบบไม่สามารถตรวจสอบได้" },
        { id: "B", text: "แจ้งว่าลูกค้าได้รับอาหารครบถ้วนตามจำนวนที่สั่งเรียบร้อยแล้ว" },
        { id: "C", text: "แจ้งว่าจะคืนเงินให้เต็มจำนวน" },
        { id: "D", text: "แจ้งให้ลูกค้าติดต่อไรเดอร์เอง" },
      ],
    },
    {
      id: "tht-plus-2026-q24",
      prompt: "หากพบว่าอาหารไม่ครบ ต้องติดต่อฝ่ายใดเพื่อแจ้งเคลมอาหาร",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 5",
      choices: [
        { id: "A", text: "ร้านค้า" },
        { id: "B", text: "ธนาคาร" },
        { id: "C", text: "IT Service" },
        { id: "D", text: "HR" },
      ],
    },
    {
      id: "tht-plus-2026-q25",
      prompt: "กรณีลูกค้าแจ้งได้รับอาหารล่าช้า ข้อมูลแรกที่ควรสอบถามคืออะไร",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 6",
      choices: [
        { id: "A", text: "หมายเลขคำสั่งซื้อ Order ID หรือเบอร์โทรศัพท์" },
        { id: "B", text: "เลขบัญชีธนาคาร" },
        { id: "C", text: "ชื่อผู้จัดการร้าน" },
        { id: "D", text: "รหัสผ่านแอปของลูกค้า" },
      ],
    },
    {
      id: "tht-plus-2026-q26",
      prompt: "การตรวจสอบเคสอาหารล่าช้า ต้องดูข้อมูลจากระบบใดบ้าง",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 6",
      choices: [
        { id: "A", text: "Admin Panel และ OPS Portal" },
        { id: "B", text: "Email และ Google Drive" },
        { id: "C", text: "Payroll และ HR System" },
        { id: "D", text: "Shopee และ Lazada" },
      ],
    },
    {
      id: "tht-plus-2026-q27",
      prompt: "เงื่อนไขที่ถือว่าไรเดอร์จัดส่งล่าช้า คือข้อใด",
      correctChoiceId: "B",
      slideNote: "อ้างอิง Slide 6",
      choices: [
        { id: "A", text: "เกิน 30 นาทีทุกระยะทาง" },
        { id: "B", text: "เกิน 1 ชั่วโมงต่อระยะทาง 10 กิโลเมตร" },
        { id: "C", text: "เกิน 2 ชั่วโมงต่อระยะทาง 5 กิโลเมตร" },
        { id: "D", text: "เกิน 15 นาทีทุกออเดอร์" },
      ],
    },
    {
      id: "tht-plus-2026-q28",
      prompt: "กรณีอาหารเสียหาย/หกเลอะเทอะ ต้องสอบถามหลักฐานอะไรจากลูกค้า",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 7",
      choices: [
        { id: "A", text: "Order ID, เมนูอาหารที่เสียหาย, รูปถ่ายอาหารที่ได้รับ" },
        { id: "B", text: "บัตรประชาชน, เลขบัญชี, สลิปเงินเดือน" },
        { id: "C", text: "ชื่อไรเดอร์, สีรถ, รุ่นโทรศัพท์" },
        { id: "D", text: "รายการโปรโมชันที่ใช้ทั้งหมด" },
      ],
    },
    {
      id: "tht-plus-2026-q29",
      prompt: "กรณีอาหารเสียหาย ต้องตรวจสอบรูปจากระบบใดเพื่อพิจารณาว่าเกิดจากไรเดอร์หรือแพ็กเกจร้านค้า",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 7",
      choices: [
        { id: "A", text: "OPS Portal" },
        { id: "B", text: "ระบบเงินเดือน" },
        { id: "C", text: "Line OA อย่างเดียว" },
        { id: "D", text: "ระบบสมัครงาน" },
      ],
    },
    {
      id: "tht-plus-2026-q30",
      prompt: "กรณีลูกค้าแจ้งไม่ได้รับอาหาร แต่สถานะจัดส่งสำเร็จ ต้องตรวจสอบข้อมูลใด",
      correctChoiceId: "A",
      slideNote: "อ้างอิง Slide 8",
      choices: [
        { id: "A", text: "สถานะออเดอร์ใน Admin Panel และรูปภาพจัดส่งสำเร็จใน OPS Portal" },
        { id: "B", text: "ยอดขายร้านค้ารายเดือน" },
        { id: "C", text: "คะแนน QA ของแอดมิน" },
        { id: "D", text: "ประวัติการลาออกของไรเดอร์" },
      ],
    },
  ],
};
