import React, { useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import PageHero from "./PageHero";
import { registerTHSarabunNew } from "./THSarabunNew-jsPDF";
import { logUsageEvent } from "./usageLog";

type UserRole = "Agent" | "Senior" | "Supervisor" | "Quality Assurance";

type UserAccount = {
  username: string;
  displayName: string;
  role: UserRole;
  agentName: string;
  email?: string;
  status?: "Active" | "Suspended";
  suspendReason?: string;
};

type CurrentUser = {
  username: string;
  displayName: string;
  role: UserRole;
  agentName: string;
  email?: string;
  loginAt: string;
} | null;

type UserRoleAdminMockupProps = {
  accounts: UserAccount[];
  currentUser: CurrentUser;
  roleOverrides: Record<string, UserRole>;
  onRolesChanged: () => void | Promise<void>;
};

const ROLE_OPTIONS: UserRole[] = ["Agent", "Senior", "Supervisor", "Quality Assurance"];

function roleBadgeClass(role: UserRole) {
  if (role === "Quality Assurance") {
    return "border-fuchsia-200 bg-fuchsia-50 text-fuchsia-700";
  }
  if (role === "Supervisor") {
    return "border-sky-200 bg-sky-50 text-sky-700";
  }
  if (role === "Senior") {
    return "border-amber-200 bg-amber-50 text-amber-700";
  }
  return "border-emerald-200 bg-emerald-50 text-emerald-700";
}

function formatDateTime(value = new Date().toISOString()) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
    timeZone: "Asia/Bangkok",
  }).format(new Date(value));
}

export default function UserRoleAdminMockup({
  accounts,
  currentUser,
  roleOverrides,
  onRolesChanged,
}: UserRoleAdminMockupProps) {
  const [savingUsername, setSavingUsername] = useState("");
  const [message, setMessage] = useState("");
  const [draftRoles, setDraftRoles] = useState<Record<string, UserRole>>({});

  const rows = useMemo(() => {
    return accounts
      .map((account) => {
        const normalizedUsername = account.username.trim().toLowerCase();
        const effectiveRole = roleOverrides[normalizedUsername] || account.role;
        return {
          ...account,
          effectiveRole,
          normalizedUsername,
          status: account.status || "Active",
        };
      })
      .sort((a, b) => a.displayName.localeCompare(b.displayName));
  }, [accounts, roleOverrides]);

  const totalUsers = rows.length;
  const activeUsers = rows.filter((row) => row.status === "Active").length;
  const seniorUsers = rows.filter((row) => row.effectiveRole === "Senior").length;
  const supervisorUsers = rows.filter((row) => row.effectiveRole === "Supervisor").length;
  const qaUsers = rows.filter((row) => row.effectiveRole === "Quality Assurance").length;

  useEffect(() => {
    setDraftRoles((currentDrafts) => {
      const nextDrafts: Record<string, UserRole> = {};
      rows.forEach((row) => {
        nextDrafts[row.normalizedUsername] = currentDrafts[row.normalizedUsername] || row.effectiveRole;
      });
      return nextDrafts;
    });
  }, [rows]);

  const handleDraftRoleChange = (username: string, nextRole: UserRole) => {
    setDraftRoles((currentDrafts) => ({
      ...currentDrafts,
      [username.trim().toLowerCase()]: nextRole,
    }));
  };

  const handleSaveRole = async (account: UserAccount, nextRole: UserRole) => {
    const normalizedUsername = account.username.trim().toLowerCase();
    const previousRole = roleOverrides[normalizedUsername] || account.role;
    if (previousRole === nextRole) return;

    if (normalizedUsername === "songpon" && nextRole !== "Quality Assurance") {
      setMessage("Songpon is locked as Quality Assurance to keep role management access safe.");
      return;
    }

    setSavingUsername(account.username);
    setMessage("");

    await logUsageEvent(currentUser, "user_role_updated", {
      tab: "user-roles",
      target_agent: account.username,
      details: {
        username: account.username,
        displayName: account.displayName,
        email: account.email || "",
        previousRole,
        newRole: nextRole,
        updatedBy: currentUser?.displayName || currentUser?.username || "",
        updatedAt: new Date().toISOString(),
      },
    });

    await onRolesChanged();
    setDraftRoles((currentDrafts) => ({
      ...currentDrafts,
      [normalizedUsername]: nextRole,
    }));
    setSavingUsername("");
    setMessage(`${account.displayName} role saved: ${previousRole} -> ${nextRole}`);
  };

  const handleExportPdf = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    registerTHSarabunNew(doc);
    doc.setFont("THSarabunNew", "bold");
    doc.setFontSize(20);
    doc.text("QA Dashboard - User Role Management", 14, 18);

    doc.setFont("THSarabunNew", "normal");
    doc.setFontSize(12);
    doc.text(`Generated by: ${currentUser?.displayName || "-"}`, 14, 27);
    doc.text(`Generated at: ${formatDateTime()}`, 14, 34);

    doc.setFont("THSarabunNew", "bold");
    doc.setFontSize(11);
    const startY = 46;
    doc.text("User", 14, startY);
    doc.text("Email", 62, startY);
    doc.text("Role", 122, startY);
    doc.text("Status", 168, startY);
    doc.line(14, startY + 2, 196, startY + 2);

    doc.setFont("THSarabunNew", "normal");
    let y = startY + 10;
    rows.forEach((row) => {
      if (y > 280) {
        doc.addPage();
        y = 18;
      }
      doc.text(row.displayName || row.username, 14, y);
      doc.text(row.email || "-", 62, y);
      doc.text(row.effectiveRole, 122, y);
      doc.text(row.status, 168, y);
      y += 8;
    });

    logUsageEvent(currentUser, "pdf_generate", {
      tab: "user-roles",
      details: { pdfType: "user_role_management" },
    });
    doc.save(`QA_User_Roles_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#fbf8ff] text-slate-950">
      <PageHero
        eyebrow="Admin Control"
        title="User Role Management"
        subtitle="Manage system access roles for QA Dashboard users and export the current role list for audit records."
        workspaceTitle="Role Governance"
        workspaceSubtitle="Central permission view for Quality Assurance administration"
      />

      <div className="mx-auto w-full max-w-[1600px] px-4 py-6 sm:px-5 lg:px-6 2xl:px-8">
        <div className="grid gap-4 md:grid-cols-5">
          <div className="rounded-[22px] border border-violet-100 bg-white p-5 shadow-sm">
            <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-violet-600">Total Users</div>
            <div className="mt-3 text-3xl font-black text-slate-950">{totalUsers}</div>
          </div>
          <div className="rounded-[22px] border border-emerald-100 bg-white p-5 shadow-sm">
            <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-emerald-600">Active</div>
            <div className="mt-3 text-3xl font-black text-slate-950">{activeUsers}</div>
          </div>
          <div className="rounded-[22px] border border-sky-100 bg-white p-5 shadow-sm">
            <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-amber-600">Senior</div>
            <div className="mt-3 text-3xl font-black text-slate-950">{seniorUsers}</div>
          </div>
          <div className="rounded-[22px] border border-sky-100 bg-white p-5 shadow-sm">
            <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-sky-600">Supervisors</div>
            <div className="mt-3 text-3xl font-black text-slate-950">{supervisorUsers}</div>
          </div>
          <div className="rounded-[22px] border border-fuchsia-100 bg-white p-5 shadow-sm">
            <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-fuchsia-600">Quality Assurance</div>
            <div className="mt-3 text-3xl font-black text-slate-950">{qaUsers}</div>
          </div>
        </div>

        <div className="mt-5 overflow-hidden rounded-[28px] border border-violet-100 bg-white shadow-[0_18px_50px_rgba(88,28,135,0.08)]">
          <div className="flex flex-col gap-4 border-b border-violet-100 bg-gradient-to-r from-white to-violet-50 px-5 py-5 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="text-lg font-black text-slate-950">Role Directory</div>
              <div className="mt-1 text-sm text-slate-500">
                Choose a new CRM-style role, then click Save Role to update that user.
              </div>
              {message ? <div className="mt-2 text-sm font-semibold text-violet-700">{message}</div> : null}
            </div>
            <button
              type="button"
              onClick={handleExportPdf}
              className="rounded-2xl bg-gradient-to-r from-violet-700 to-fuchsia-600 px-5 py-3 text-sm font-bold text-white shadow-[0_14px_30px_rgba(109,40,217,0.22)] transition hover:opacity-95"
            >
              Export PDF
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="min-w-full border-collapse text-left text-sm">
              <thead>
                <tr className="bg-slate-950 text-white">
                  <th className="px-5 py-4 font-bold">User</th>
                  <th className="px-5 py-4 font-bold">Email</th>
                  <th className="px-5 py-4 font-bold">Current Role</th>
                  <th className="px-5 py-4 font-bold">Edit Role</th>
                  <th className="px-5 py-4 font-bold">Action</th>
                  <th className="px-5 py-4 font-bold">Status</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => {
                  const isSongpon = row.normalizedUsername === "songpon";
                  const draftRole = draftRoles[row.normalizedUsername] || row.effectiveRole;
                  const hasRoleChange = draftRole !== row.effectiveRole;
                  return (
                    <tr key={row.username} className="border-b border-slate-100 last:border-b-0">
                      <td className="px-5 py-4">
                        <div className="font-black text-slate-950">{row.displayName}</div>
                        <div className="mt-0.5 text-xs font-semibold text-slate-500">{row.username}</div>
                      </td>
                      <td className="px-5 py-4 text-slate-600">{row.email || "-"}</td>
                      <td className="px-5 py-4">
                        <span className={`inline-flex rounded-full border px-3 py-1 text-xs font-black ${roleBadgeClass(row.effectiveRole)}`}>
                          {row.effectiveRole}
                        </span>
                      </td>
                      <td className="px-5 py-4">
                        <select
                          value={draftRole}
                          disabled={savingUsername === row.username || isSongpon}
                          onChange={(event) => handleDraftRoleChange(row.username, event.target.value as UserRole)}
                          className="min-w-[190px] rounded-2xl border border-violet-100 bg-white px-4 py-2.5 text-sm font-semibold text-slate-800 outline-none transition focus:border-violet-500 focus:ring-4 focus:ring-violet-100 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400"
                        >
                          {ROLE_OPTIONS.map((role) => (
                            <option key={role} value={role}>
                              {role}
                            </option>
                          ))}
                        </select>
                      </td>
                      <td className="px-5 py-4">
                        <button
                          type="button"
                          disabled={!hasRoleChange || savingUsername === row.username || isSongpon}
                          onClick={() => handleSaveRole(row, draftRole)}
                          className="rounded-2xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white shadow-sm transition hover:bg-violet-800 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400"
                        >
                          {savingUsername === row.username ? "Saving..." : "Save Role"}
                        </button>
                      </td>
                      <td className="px-5 py-4">
                        <div className={`inline-flex rounded-full border px-3 py-1 text-xs font-black ${row.status === "Active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>
                          {row.status}
                        </div>
                        {row.suspendReason ? <div className="mt-1 text-xs text-slate-500">{row.suspendReason}</div> : null}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
